* 非思量分别之所能解，唯有实修亲证
  # 持续不断的努力，并常自问，能否更努力一点。
** 十份时间，一份阅读一份交流八分实修。 谨守身口意
1. 熟读成诵。博学多闻，有助宣说，对实证并非必需
   一段一段慢慢读 细细读 保持正念的读
   广闻博览 http://wiki.sutta.org/wiki/%E5%85%AB%E6%88%92
2. 戒
3. 观息 定
4. 内观 慧
戒，摧毁言行的不当；定，摧毁思想的不当；慧，摧毁潜在的不净。
** 独处。只有自己。慎独
** 三法印，四谛，八正道
   无常、苦、无我
   苦、集、灭、道
   戒（正语、正业、正命）定（正精进、正念、正定）慧（正见、正思维）

   布施/乐于助人、持戒/严于律己、忍辱/不卑不亢、
   精进/谦虚勤奋、禅定/专注坚定、般若/公平无私
   
   纪律和道德、耐心和毅力、专注与内观、慈悲和爱心
   注意知识、力量和智能的不同
   根器和业力，因缘，十二因缘？
   # 三十七道品：四圣谛、四正勤、四神足、五根、五力、七觉支、八正道。
*** 异议：任何事物都有两面性，有苦必有乐？
	矛盾无时不有，无处不在。
	乐？乐的产生、乐的消失、获取乐的方法
	有哪些让我们快乐的东西？
	好吃的，好看的，好听的，好闻的，好玩儿的，
	舒适的，凉爽的，温暖的，柔滑的，安全的，
	顺心的，如愿了，被赞赏，被接受，被认同，被关心，
	被需要，能助人，
	没有债，充实而不忙碌，
	有理想并为之奋斗，有信念，有能力，有钱，
	经过努力后的收获，
	有知己
	感恩，原谅，知足，诚实守信，专注，认真，努力，坚持，
	良师益友，同情心，学而时习之，布施，慈悲，放下，照顾好自己，
	解决问题，做想做的事，活在当下，笑，冥想，
	
	知足常乐 but 知足，何其难！
	# 能让自己快乐起来的人更能得到更多的快乐！ 为什么不快乐呢？要快乐。
	美味，音乐，歌舞，轻松，健康，
	舒爽，畅快，赞赏，顺心，信仰，
	如愿，敬畏，权力，财富，助人为乐，，，
	它们来时带着快乐满足，它们去时留下烦恼空虚

	需求层次理论； 满足需求就会快乐。
	五类：生理需求、安全需求、社交需求(爱和归属感)、尊重需求和自我实现需求。
	1. 呼吸、水、食物、睡眠、生理平衡(健康）、分泌、性。
	2. 人身安全、健康保障、资源所有性、财产所有性、道德保障、工作职位保障、家庭安全
	3. 友情、爱情、性亲密
	4. 自我尊重、信心、成就、对他人尊重、被他人尊重
	5. 道德、创造力、自觉性、问题解决能力、公正度、接受现实能力
	6. 自我超越
	衣食无忧、安全、
对于不同年龄段的人会有不同的看法：
小孩子会觉得：生活中最快乐的事就是每天不用写作业，无忧无虑的玩儿。
有糖果零食，有动画片
青少年则认为：作业量不用太多，可以有闲暇的时间用来搞自己喜欢并且感兴趣的事。
青年们认为：每天打游戏，出去旅游。
成年人则想着和自己心爱的女友环游世界是最快乐的事。
中年人认为：全家人一块儿在一起吃饭，睡觉，逛公园是最快乐的事。
老年人认为：自己的儿女能常回家看看，一起吃一个团圆饭则是最快乐的事。
总之，有一颗良好的心态，那才是最快乐的事~~~~	

* 一切都失去了光彩，失去了意义
  任何的安慰，各种鸡汤，都显得苍白乏力
  何时？
  幻象？真实？

  预期 憧憬 想象 幻想 | 现实 真实
  
极限法，最极端的情况，认清问题本质。
如，世界上所有人都让你觉得丑陋和讨厌，还有什么奋斗的动力吗？
你拥有全知全能的力量，一切都在你想要的瞬间实现，还有什么乐趣吗？
* 信
  佛陀做为心灵导师的成功程度，完全取决于他训练弟子的技巧。

经典中为礼敬佛陀而称他为“无上士调御丈夫”①，
要检验这句话的真实度，就必须去看他所指导的男女弟子的气度。
就如太阳的价值，不只在它本身的光明，同时也在它照亮世间的能力一样。
因此，佛陀作为心灵导师的光辉，不只是取决于他教法的清晰度，
更是在他能启发前来求皈依者与因材施教。缺少弟子团体见证它转化的力量，
“法”（Dhamma）将只是学说与严谨修持的包裹，徒有令人钦佩的清晰与精确的理智，
但都与活生生的人无关。“法”只有在接触生命，提升它的追随者，
经他们转化为智慧、慈悲与清净的典范时，“法”才会有生命。

* 上班地铁上想起一个话题
每一天如何过才是有价值的呢？ 有钱有名有闲有健康有声色犬马
人生天地之间，若白驹过隙，忽然而已 ―― 庄子《知北游》

 有没有价值，有个非常简单的标准：每天是不是快乐开心。 就可以判断。
 如果发现自己常常不高兴，甚至每天都不高兴，那就一定出问题了。
 快乐就好。
 话是这样说， 还是有许许多多人是苦苦的过着每分每秒，或是麻木的过着分分秒秒。
对酒当歌，人生几何？譬如朝露，去日苦多。
青青子衿，悠悠我心；何以解忧？唯有肚肠

 有没有想过自己的三年五年或十年的目标？
 那么人生的目标呢？
 几个非常明确的例子：
 佛教是证入涅，基督教是进入天国，马克思主义者是共产主义，秦始皇是统一六国，
 体育运动员是金牌（挑战极限，突破极限），一般人是“成功”：有名有钱有时间，有健康

 # 什么是有益的,有价值的,被圣人称赞的，能导向涅的
 另一层面，生物界一个共同的目标是繁衍后代，传宗接代。
 追逐和享受感官欲乐，

・ 人生应该如蜡烛一样,从顶燃到底,一直都是光明的.―― 萧楚女
・ 人只有献身于社会,才能找出那短暂而有风险的生命的意义.―― 爱因斯坦
・ 人生的价值,即以其人对于当代所做的工作为尺度.―― 徐玮 
・ 但愿每次回忆,对生活都不感到负疚 ―― 郭小川 
・ 你若要喜爱你自己的价值,你就得给世界创造价值.―― 歌德 
・ 人生不是一种享乐,而是一桩十分沉重的工作.―― 列夫 ・ 托尔斯泰 
・ 人生的价值,并不是用时间,而是用深度去衡量的.―― 列夫 ・ 托尔斯泰
生命中真正重要的不是你遭遇了什么，而是你记住了哪些事，又是如何铭记的。――马尔克斯《百年孤独》
一个人知道自己为什么而活，就可以忍受任何一种生活。―― 尼采

作者：罗鹏
链接：https://www.zhihu.com/question/20447176/answer/19587501
人生观，你想成为什么样的人？
人生观是你对自己这一生总体的期待，你觉得作为一个人，就应该这样这样这样。
比如你是想成为有钱人，过别人羡慕的富裕生活；
还是想成为高官，用权力来服务人民(也可能是为了赚钱)；
还是想成为一个旅行者，去体验世界的精彩；
还是想成为一个老师，教书育人；
还是想成为一个有思想的人，有智慧的人，不让自己活得糊涂；
还是就想做一个普通人，有车有房，安稳的过日子......

价值观，对你来说什么更重要？人在做决定的时候，都会依靠内心的一套价值体系，
选择一个相对而言更值得的去做。
在你的这个价值体系里面，借钱的时候金钱更重要还是朋友更重要，
找女朋友的时候外表更重要还是品行更重要，跳槽时薪水更重要还是平台发展更重要，
周末享受生活更重要还是为事业学习更重要......

世界观，世界是什么样的？整体来说，世界观是庞杂的、模糊的。
但这不重要，重要的是要认识到世界是客观的，
我们中的大部分人都习惯于带着成见去看待现实世界，并把偏见强加于自己的现实观。
我们学会了依靠观念来理解现实（而不是通过观察），去假定现状与我们观念中预想的相似，
这比自己亲眼观察现状要来得方便。
举个例子，我个人认为世界是由需求驱动的，你是个什么样的人不重要，
重要的是你能满足别人什么需求。

最后强调一点，人生观、价值观、世界观是不断变化的，根据你的知识结构、
主观意识的改变而改变，这也是一个再正常不过的过程，永远没有极致。


任何一件事情，只要心甘情愿，总是能够变得简单。 ――安妮宝贝《彼岸花》

所有的大人都曾经是小孩，虽然，只有少数的人记得。
令她反感的，远不是世界的丑陋，而是这个世界所戴的漂亮面具。
每个圣人都有不可告人的过去，每个罪人都有洁白无瑕的未来。

这是一个最好的时代，这是一个最坏的时代； 
这是一个智慧的年代，这是一个愚蠢的年代； 
这是一个光明的季节，这是一个黑暗的季节； 
这是希望之春，这是失望之冬； 
人们面前应有尽有，人们面前一无所有； 
人们正踏上天堂之路，人们正走向地狱之门。
  ―― 狄更斯《双城记》

井蛙不可以语于海者，拘于虚也；夏虫不可以语于冰者，笃于时也；曲士不可以语于道者，束于教也。
――庄子《秋水》
从来没有人读书，只有人在书中读自己，发现自己或检查自己。 ―― 罗曼・罗兰

* 障碍 束缚 结使

这些难关便是：

贫穷时，布施助人难
富贵时，学习佛法难
舍弃自己的性命难
能够听经学佛难
生在佛法在世的时代难
控制自己的感情欲望难
遇到珍贵东西不奢求难
被侮辱不嗔恨难
有权势不居高难
与外境接触不动心难
广泛学习博览群书难
消灭自我的傲慢难
不轻视不懂学法的人难
对万物持平等心难
不说是非对错难
遇到大德善知识难
明心见性地学习难
随缘教化他人难
遇到境界并不为所动难
明白方便法以教化众生难

这二十难，我们需要记在心里，作为对境，时时自省吾身......

* 思
贪求、执取
预期 憧憬 想象 幻想 | 现实 真实

最小化，能不做就不做；最大化，力所能及的多做。 转变，时间如何度过？

获取关注 认同 或敬畏。喂养六条饿狼，眼耳鼻舌身意，六欲

最终的大boss - 性

存在感 我见 是怎么产生的？

学深刻地体验到真正的空无自性，是极大的喜悦，此时心变得无所执取，并且清澈而明亮。
如何验证？ 找到最“在意”的，丢弃它会怎样？ 比如，删掉收藏的图片视频文章好友等等
如何检验？ 若有良田千顷，家奴无数，富贵荣华，会否舍弃一切，清修悟道？

昏沉 散乱 邪淫 难戒 如之奈何？ 如何做？ 熟读成诵，如健身一样奋力锻炼心力
平静平稳、警觉专注、非常的警觉非常的专注、十分的警觉十分的专注

休息，而不是放弃

忽然想到一个游戏， 如果人和人交往的时候，完全诚实， 会是一种什么状况？

勿顾虑别人的过失，也勿顾虑别人有否作善或作恶；只须留心自己的过失，以及留心自己有否作善或作恶。
常思己过，莫论他非。

兴高采烈  欢欣鼓舞； 无精打采 百无聊赖

* 闻
http://www.dhammarain.org.tw/magazine/new/dhammarain-mag-004.html
http://www.dhammarain.org.tw/
http://www.dhammarain.org.tw/magazine/rainall.html

   本书是一部心灵之旅，它带领你参访许多佛法的系统和师父。
表面上，他们也许各有不同，甚至彼此矛盾，
然而，我们无须相互比较，评定优劣。
这些言语和系统底下都是唯一真理的不同展现。
法是不变的，正如草叶的低垂和云朵的飘动显示有风的存在，
大师们的文字和教诲也都指向相同的体验、相同的真理。

大唐西域记，瑜伽师地论，成唯识论

本书最有效的使用方式，是依照它们最初的写法，
即为了激励与薰陶心灵的目的而阅读；不应存着阅读小说的心态来读。
在此建议读者，一天最好不要阅读超过一章，
应该和你正在学习的某个特殊弟子“交朋友”，
思维他或她的生命与教导，并试着发现那些故事对现代人有何启发。
最快也要等到隔天，才可以进行下一章。
你的心可能会迷恋这些事，因此最好克制一下好奇心，
并不断提醒自己为何阅读这本合集的原因。


沙利子是个名副其实的真实朋友，他了解如何做对别人最有利，
像佛陀所描述的理想朋友一样，直言不讳地指出朋友的过错，毫不迟疑。
就是透过这种诚实的批评，他帮助阿奴卢塔尊者突破最后关卡，证得阿拉汉果，
如《增支部》的记载：

有一次阿奴卢塔去看沙利子，相互寒暄之后，他便坐下来对沙利子说：
“沙利子吾友，我以超越世人眼界的清净天眼，可以看见大千世界。
我精进不懈，正念、正知且无疑惑；我的身体平静无忧扰，我的心专注于一处。
然而，我的心却仍未从烦恼与贪着中解脱。”
“阿奴卢塔吾友，”沙利子说，“当你想到你的天眼时，慢心就生起了；
当你想到自己坚定的精进、正念、无忧扰的色身与专注一处的心时，掉举就产生了；
当你想到你的心不能从烦恼解脱时，这就是恶作。如果你能舍弃这三种心境，
不再注意它们，这将会对你有所助益，就能将心引导到‘不死界’。”

阿奴卢塔遵从沙利子的建议，很快便断除烦恼。


现实中很多人把爱情理想化，缺乏现实感，总希望自己的爱情像小说电视剧那般浪漫：
月白风清，白马王子突然从天而降；一见钟情，爱情之花突然奇迹般地大放光彩

* 疑 疑问 疑虑 
疑虑：都出家，人类就消失了; 耕作者出家了，其他家人怎么办？
疑问：若无一个延续不断的灵魂，那么业报是如何运作的呢，承受者是谁呢？

闻思修 戒定慧  信愿行 佛法僧

* 修
所做的，所拥有的，能否使心灵更美好？身体更健康？赢得尊重？带来财富？
* 读书，并非百利无害
  非圣书，屏勿视，蔽聪明，坏心志。
  过犹不及，不要花费太多时间读书。
  万般皆下品惟有读书高，警惕这种优越感。
  纸上谈兵，变成书呆子。尽信书则不如无书。
  读书使人明智，但明智的后果未必是带来快乐。

* 7种让人越来越蠢的认知偏差
  https://www.zhihu.com/question/37723905
https://mp.weixin.qq.com/s?__biz=MjM5NTU0NTYxNA==&mid=2652647409&idx=1&sn=f6b0a9b701b85eb2bec60f6b0c23714f&chksm=bd1e58908a69d186407cf8096a546c5d65f297d45d283e816617e176ff97b619b9196bd32410&mpshare=1&scene=1&srcid=08103CGa3dZ4da8oAKjT2bzG#rd
1.自利归因偏差(self-serving bias）
成功时，觉得多半是自己的功劳；失败时，甩锅给别人或外界环境。
# 对治：常思己过，莫论他非

2.行动者-观察者偏差(actor-observer effect)
我们观察别人的行为时，倾向于指责别人的人品，而忽视情境的影响。
人在矮檐下，怎能不低头
# 对治：设身处地，换位思考

3.错误定价（misvaluation hypothesis）
你对一件事的定价，就是你认为，这件事带给你的价值。
之所以会有错误定价偏差，是因为很多人，只定价了一件事的短期价值。
例，明明知道电子游戏，休闲时玩一玩即可，可很多人心中，游戏的「定价」奇高，因为追求即时的愉悦感，他们打游戏茶饭不思。
读书学习，短期看不到价值，他们便放弃；游戏，短期获得了快感，就拼了命地玩。
# 对治：？

4.过度自信偏差（overconfidence theory）
如果你正确定价了读书，明白读书的重要了……还可能陷入另一种偏差。
比如「今年我一定要读100本书！」，或者朋友圈集赞「你们给我点几个赞，今年我就要读几本书！」。
心理学家把人的这种迷之自信，叫做过度自信偏差。
# 对治：看看自己的前半生，做个简单的计划，行动吧

5.沉没成本效应(sunk cost effects)
上高中那会，共享车还没出世，有时早上起迟了，准备打的却苦苦等不到，反倒是公交车过去好几辆，我却还是想打的，
心想：“我都等了这么久的的士，得继续等下去，要不然先前花的时间不白费了？”

我的做法其实是很蠢的，这是典型的沉没成本效应。
等的士花的时间，就是我不可挽回的成本，却影响了我的决策，宁愿继续等下去也不愿坐公交……

谈恋爱时也一样，对方毅然决然提分手，你心想：“都谈一年了，付出了那么多，怎能轻易结束？”
可……Ta已经不爱你了，挽留不成，却还是要死缠烂打。
这不是蠢，是什么？
过去的牺牲和付出，就让它过去吧，如果不能把过去的痛苦和牺牲留在身后，那和身居牢狱有什么区别？
# 对治：站在当下，往前看
6.后视偏差（hindsight bias）
事后诸葛亮，事前猪一样。
# 对治：事先做足准备工作；丑话说在前头
7.幸存者偏差（survivorship bias）
常常看见这样的报道： 从月薪3000逆袭估值30亿估值企业CEO，他有什么秘诀？
打开文章，通常先讲一个潘磕嫦的故事，然后总结出123条道理，告诉读者这就是秘诀……
心理学家称之为幸存者偏差，千千万万个月薪3000的人里，只有他是「幸存者」，上了媒体报道，其他99.9%的人都「死了」。

大部分人只看到成功人士讲的大道理，却没看到背后的方法论、资源、家境、人脉甚至运气成分。
# 对治：

远离认知偏差，有这3个步骤：
1.改变你的元认知
认识到认知偏差的存在本身，就能削弱它的影响。

这个过程，其实调用你的元认知能力，即对思考过程的反思：
只有意识到思考过程中偏差的存在，才能去改变它，元认知为思考过程按下了停止键。

2.没错，你应该对号入座
认识到还不够，现实里的认知偏差往往很隐蔽，所以一定要联系你的现实经历。
比如：过去我犯过哪些偏差？将来，碰到同样的情况，才会想起来去避免。

3.慢下来，慢下来，慢下来
每天都能看到这样的标题：
几节课颠覆你的认知，几天教你把月薪提高十倍，几条秘诀教你成为高手……

无数的课程、文章，都号称能颠覆你的三观。
于是你心动了，点了购买，去感受「迅速」颠覆三观的感觉。

这个时代太「快」了。
它鼓动你迅速成功、鼓动你迅速购买、鼓动你迅速思考......

商家利用人性、利用心理陷阱、利用认知偏差，操纵你的钱包。
所以我建议你：在做任何决定前，给自己一些思考的时间，慢下来，慢下来，慢下来。

快，是时代病。
慢，是良药。

* 价值或意义
  人的生存只有两种：“美丽的活着”，亦或“为美丽的人活着”。――尼克 《东京食尸鬼》

如是思维，
看着男神女神的照片，能获得什么呢？能带来什么益处呢？
能让心灵更美好吗？能让身体更健康吗？能赢得尊重吗？还是能带来财富？
美是功利。
看到，触到，得到，拥有认为美的、吸引你的，从中能获得什么呢？能带来什么益处呢？
能让心灵更美好吗？能让身体更健康吗？能赢得尊重吗？还是能带来财富？

看到美图，看到视频，看到完全符合自己心意的图片或照片，看到精彩细腻的故事文章，看到完全符合自己心意的实践视频，
从中能获得什么呢？某种感觉
这能带来什么益处吗？
能让心灵更美好吗？能让身体更健康吗？能赢得尊重吗？还是能带来财富？让生活更快乐？

看到，触到，得到，甚至拥有你认为美的、吸引你的东西或人，
从中能获得什么呢？还是某种感觉？更强烈一些的感觉？还有其他？
能带来什么益处呢？
能让心灵更美好吗？能让身体更健康吗？能赢得尊重吗？还是能带来财富？让生活更快乐？

心是欲的奴隶，身是心的马车。
每个圣人都有不可告人的过去，每个罪人都有洁白无瑕的未来。
苦海无边回头是岸。愿一切众生，无敌意，无危险，无身体的痛苦，无心灵的痛苦。
戒，摧毁言行的不当；定，摧毁思想的不当；慧，摧毁潜在的不净。

* 欲乐的过患？
首先 从理智上看清各种欲望和快乐是无益而虚幻不实的；然后 拔除对欲乐的追逐根源。
纵是虚幻也是快乐，干嘛要去除呢？ 仍然需要先从理智上认清，带来的过患？？
# 要拔除它仅靠理智是办不到的。如之奈何？
戒定慧
戒，摧毁言行的不当；定，摧毁思想的不当；慧，摧毁潜在的不净。

# 辛勤工作，努力奋斗，追求理想，是否是为了满足身心的各种欲求呢？
若世上只剩你一个人，还会有辛勤工作，努力奋斗，追求理想吗？
或者所有人都让你觉得丑陋而讨厌，还会有辛勤工作，努力奋斗，追求理想吗？
或者此生无望遇不到一个令你欣赏喜欢的人，还会有辛勤工作，努力奋斗，追求理想吗？

问：我们能否充分感觉和享受事物，同时又保持平等心？
答：当然可以。生命是要来享受有益于善的事物。但是不可以对任何事物起执着。
你保持平等心和享受，那么当你失去它时你泰然微笑：
「我就知道它会离开的。它已经离开了。有什么大不了？」那么，你才是真正地在享受生命。
否则，你变得执着，而如果你失去它，你将卷入痛苦中。所以不要痛苦。要在每个情况下都快乐。

# 感官欲乐的过患
https://www.douban.com/note/173085216/
《小部.法句经》：纵使天上下起金币之雨，我们的感官之欲也不会满足。‘它们是苦，远非乐。’
了悟此意后智者知道，纵使在天界般的感官之娱里也无乐可得。他是正自觉者的弟子，以终结感官欲望为乐。
 
《中部.哺多利经》：“假定一只狗，为虚弱与饥饿所困，路过一座屠宰场，有个技熟的屠夫或其学徒，朝它扔一串骨――刮净、沾血、无肉。
你们觉得如何：那只狗，啃着那串骨――刮净、沾血、无肉――它的虚弱与饥饿可会消解？ ”
“世尊，不会的。为什么呢？因为那串骨被刮净、沾血、无肉。那只狗除了疲倦与恼怒，什么也得不到。”
“家主们，同样地，一位圣者的弟子如此思索：‘世尊把感官欲乐比作一串骨，苦多、绝望多、过患更多。’
以正明辨如实看清了这一点，他会避免来自多种因素、依赖多种因素的安宁，培养来自单一因素、依赖单一因素的安宁，
由此止息对世俗之诱的执取与维持，不着余迹。”
 
《中部.苦蕴大经》：“何为感官欲乐的诱惑？比丘们，感官欲乐有五条。哪五条？
藉眼识别之色――愉悦、可喜、迷人、可爱、增欲、诱人。藉耳识别之声……藉鼻识别之香……藉舌识别之味……
藉身识别之触――愉悦、可喜、迷人、可爱、增欲、诱人。
有赖于这五条感官欲乐而生的喜与乐，那便是感官欲乐的诱惑。

那么，何为感官欲乐的过患？有此情形，一位族姓子从业谋生――无论会计、算师、耕作、商贾、牧牛、箭手、国王随从，等等
――他面对冷、他面对热、受蚊蝇爬虫骚扰、风吹日晒、死于饥渴。”
“感官欲乐的这个过患，即时即地可见的这一堆苦，是以感官欲乐为由、以感官欲乐为源、以感官欲乐为因、只为了感官欲乐。
这位族姓子若这般辛苦操劳，却不得财富，他于是忧愁、悲痛、哀叹、捶胸、痛苦。我的工作徒劳无获、我的辛劳毫无结果！
因此，感官欲乐的这个过患，即时即地可见的这一堆苦，也以感官欲乐为因……
“这位族姓子若这般辛苦操劳，得了财富，他便经历守护之忧苦:
‘如何不让国王、盗贼抢走我的财物，如何不让它给火烧毁、给水冲走、给不孝子孙夺走?’
正当他守护、看护财物时，它却给国王、盗贼抢走、给火烧毁、给水冲走、给恨心子孙夺走了。
他于是忧愁、悲痛、哀叹、捶胸、痛苦。‘我的财物尽失去了!’ 
因此，感官欲乐的这个过患，即时即地可见的这一堆苦，也以感官欲乐为因……
       
“再者，正是以感官欲乐为由、以感官欲乐为源、以感官欲乐为因、只为了感官欲乐，
国王与国王相争、贵族与贵族相争、僧侣与僧侣相争、家主与家主相争、母与子相争、
子与母相争、父与子相争、子与父相争、兄弟与兄弟相争、兄弟与姊妹相争、姊妹与兄弟相争、
友与友相争。接着，他们在争执、争闹、争论时，以拳、以土块、以棒、或以刀相互攻击，
招致死亡或如死之痛。" 因此，感官欲乐的这个过患，即时即地可见的这一堆苦，也以感官欲乐为因……
# 冲冠一怒为红颜 人为财死鸟为食亡 天下熙熙皆为利来，天下攘攘皆为利往。

“再者，正是以感官欲乐为由、以感官欲乐为源、以感官欲乐为因、只为了感官欲乐，
人们执起剑盾、架起弓矢、聚为两阵、冲进战场，一时矢矛纷飞、剑光闪闪;
在那里他们为矢矛刺伤、被刀剑砍头，招致死亡与如死之痛。
因此，感官欲乐的这个过患，即时即地可见的这一堆苦，也以感官欲乐为因……
       
“再者，正是以感官欲乐为由、以感官欲乐为源、以感官欲乐为因、只为了感官欲乐，
人们执起剑盾、架起弓矢、冲击陡滑的堡垒，一时矢矛纷飞、剑光闪闪; 
在那里他们受沸牛粪泼撒、被重物砸扁、给刀剑砍头，招致死亡或如死之痛。
因此，感官欲乐的这个过患，即时即地可见的这一堆苦，也以感官欲乐为因……
       
“那么，何为感官欲乐的解脱？凡是平息对感官欲乐的贪爱、放弃对感官欲乐的贪爱，那便是感官欲乐的解脱。”
 
《中部.苦蕴大经》：“比丘们，何为形色之诱？假定有一位贵族、婆罗门、或家主阶级的少女，
十五六岁、不高亦不矮、不胖亦不瘦、不黑亦不白。她的美貌与魅力可是在最盛之时？”
“世尊，是的。”
“凡有赖于该美貌与魅力而升起的喜与乐：那便是形色之诱。
       
“那么，何为形色之诱的过患？有此情形，人们可能后来再见同一位女子八十、九十、百岁之相：
衰老、如橼木般弯曲、佝偻、持杖、抖索、衰弱、豁牙、白发、少发、秃发、皮皱、肢体多斑。
你们以为如何：是否她昔日的美貌魅力已然褪尽，过患显现？”
“世尊，是的。”
“比丘们，这便是形色之诱的过患。
       
“再者，人们可能再见同一位女子在病患、痛苦、重疾之中，卧于屎尿之污、靠他人抬起放下。
你们以为如何: 是否她昔日的美貌魅力已然褪尽，过患显现？”
“世尊，是的。”
“比丘们，这也是形色之诱的过患。

“再者，人们可能再见同一位女子弃尸坟场――一日、两日、三日，肿胀、青紫、腐烂。
你们以为如何: 是否她昔日的美貌魅力已然褪尽，过患显现？”
“世尊，是的。”
“比丘们，这也是形色之诱的过患。

“再者，人们可能再见同一位女子弃尸坟场，为乌鸦、鹰鹫、为狗、土狼等动物啄食……
骨胳尚有血肉、以筋相连……骨胳血肉尽失、以筋相连……
骨腱分离、散乱四处――此处手骨、彼处足骨、此处腓骨、彼处腿骨、此处臀骨、彼处椎骨、
此处肋骨、彼处胸骨、此处肩骨、彼处颈骨、此处腭骨、彼处齿牙、此处头骨……
骨色发白如螺壳、经年堆积……化为粉末……
你们以为如何: 是否她昔日的美貌魅力已然褪尽，过患显现？”
“世尊，是的。”
“比丘们，这也是形色之诱的过患。

“那么，比丘们，何为出离形色? 平息对形色的贪爱、放弃对形色的贪爱，那便是出离形色。
“凡不能如实明辨形色之诱惑为诱惑、形色之过患为过患、形色之出离为出离的僧侣行者，
他们自己理解形色、或以此真理激励他人藉修持了解形色: 那是不可能的。
然而，凡能如实明辨形色之诱惑为诱惑、形色之过患为过患、形色之出离为出离的行者，
他们自己理解形色、或以此真理激励他人藉修持了解形色: 那是可能的。”
 
“那么，比丘们，何为感受之诱？有此情形，一位比丘――远离感官欲乐、远离不善巧心态――
进入、安住于第一禅那: 由远离而生起喜与乐、伴随着寻想与评量。
那时候，他无心伤害自己、伤害他人、或伤害双方。他有一种彻底无害的感受。
我告诉你们，此无害之受，乃是一切感受中的至高诱惑。
       
“接着这位比丘，随着寻想与评估的平息，进入、安住于第二禅那; 由沈静而生起喜与乐，
随着寻想与评量的消退、知觉汇合起来――有了内在确定……
随着喜的消退，他保持着宁静、有念、警觉，身体敏感于乐。他进入、安住于第三禅那，
对此圣者们宣告:‘宁静、有念，他有了愉快的居处’……
随着乐与痛的放弃――如先前喜与苦的消退一般――他进入、安住于第四禅那:
 宁静与念住达到纯净，既无乐、又无痛。那时候，他无心伤害自己、伤害他人、或伤害双方。
他有一种彻底无害的感受。我告诉你们，此无害之受，乃是一切感受中的至高诱惑。
       
“那么，何为感受的过患？感受无常、有苦、可变: 这便是感受的过患。
那么，何为出离感受？平息对感受的贪爱、放弃对感受的贪爱，那便是出离感受。
凡不能如实明辨感受之诱惑为诱惑、感受之过患为过患、感受之出离为出离的僧侣行者，
他们自己理解感受、或以此真理激励他人藉修持了解感受: 那是不可能的。
然而，凡能如实明辨感受之诱惑为诱惑、感受之过患为过患、感受之出离为出离的僧侣行者，
他们自己理解感受、或以此真理激励他人藉修持了解感受: 那是可能的。”
 
《增支部.六集》：“那么，何为对过患的辨识、认知？
有此情形，一位比丘――来到野外、树下、空静之处――如此思索:‘这色身有诸多痛苦、诸多过患。
在这色身里会升起诸多疾病，如: 视力病、听力病、鼻病、舌病、体病、头病、耳病、口病、
牙病、咳嗽、哮喘、粘膜炎、热病、衰老、胃痛、昏迷、痢疾、流感、霍乱、麻疯、疔疮、
轮癣、肺结核、癫痫、皮肤病、痒症、痂、干癣、疥疮、黄疸、糖尿、痔疮、瘘管、溃疡、
胆症、粘液症、风症、体液症、气候症、身体照顾不周之症、外伤、业力病、冷、热、饿、
渴、排屎排尿。’ 他这般地专注于色身的过患。这便称为对过患的辨识、认知。”
 
《增支部.四集》：“这四种追求是尊贵的。哪四种？
有此情形，一个人，自己会衰老，意识到衰老的过患，寻求脱离枷锁、不老、无上的止息: 即解脱。
自己会染病，意识到染病的过患，寻求脱离枷锁、无病、无上的止息: 即解脱。
自己会死亡，意识到死亡的过患，寻求脱离枷锁、不死、无上的止息: 即解脱。
自己有杂染，意识到杂染的过患，寻求脱离枷锁、无杂染、无上的止息: 即解脱。”
 
《增支部.七集》：怒者丑陋、少眠，他所得盈利，因言行有失，转为亏损。
盛怒的人，把他的财富摧毁。狂怒的人，把他的地位摧毁。亲戚、朋友、同事们躲避他，
嗔怒带来损失，嗔怒使心燃烧。他意识不到危险由内心生起，怒者不了解自己的利益，怒者看不见法。
被嗔怒征服的人，处于一团阴暗之中。他乐于恶行，以为善行，当怒意消退之时，他如火烧般受苦。
他如烟雾围绕之火，无用、无光。
 
《相应部》：一切执取现象的过患：
“一个人连续专注于执取现象的过患，渴求便止息了。从渴望的止息，引致执取、维持的止息。
从执取、维持的止息，引致缘起的止息。从缘起的止息，引致生的止息。
从生的止息，于是老、病、死、忧、哀、痛、悲、惨，全部止息。若大一堆苦与紧张，便是这般地止息。”

《增支部.九集》：其时，尊者阿难与家主塔普萨往诣世薄伽梵，近前顶礼后，坐于一边。坐下后，他对薄伽梵说：
“这位家主塔普萨对我说：‘尊者阿难，我们是耽溺于感官之乐、欣喜于感官之乐、享受感官之乐、纵情感官之乐的家主。
在我们这些耽溺于感官之乐、欣喜于感官之乐、享受感官之乐、纵情感官之乐的人看来，出离根本是个大损失。
然而，我却听说此法此律之中，年轻的比丘们视出离为宁静，内心急于出离，趋向有信心、稳步、坚定。
因此正是在出离这个主题上，此法此律与大众背道而驰。’”
       
“正是如此，阿难，正是如此。即便我自己在觉悟前、尚为未悟的菩萨时，虽想到：‘出离善哉。退隐善哉，’然而我的心却不急于出离，未视出离为宁静，未趋向有信心、稳步、坚定。我想：‘是何因缘、是何理由，为什么我的心不急于出离，未视出离为宁静，未趋向有信心、稳步、坚定?’ 接着我想到：‘我还不曾看见感官欲乐的过患。我还不曾思考那个主题。我还不理解出离的果报。我对它还不熟悉。那就是为什么我的心不急于出离，未视出离为宁静，未趋向有信心、稳步、坚定。’”
       
“接着我想到：‘如果看见了感官欲乐的过患后，我思考该主题; 如果理解了出离的果报后，我对它熟悉起来，我的心便有可能急于出离，视出离为宁静，趋向有信心、稳步、坚定。’”“于是后来，在看见了感官之乐的过患后，我探索该主题，在理解了出离的果报后，我使自己熟悉它。我的心急于出离，视出离为宁静，趋向自信、稳步、坚定。接下来，远离感官之欲、远离不善巧的心态，我进入、安住于初禅: 从远离中升起了喜与乐，伴随着寻想与评量。”
 
《小部.自说经》――佛陀：“跋提，听说你独自在林中、树下、空静处，反复大叫 ‘极乐! 极乐!’可是真的？” 尊者跋提：“世尊，是真的。”“你反复大叫‘极乐! 极乐!’时，心里在想什么？”尊者跋提：“过去，在我居家时，为了常享君王的喜乐，我把卫兵部署于王宫内外、城镇内外、乡村内外。即便有这等保护、这等守护，我仍住于怖畏――焦躁、多疑、恐惧。但现在，独自去林中、树下、空静处时，我住于不惧、不躁、自信、无畏――不担心、不困扰，我的需要满足了、我的心如野鹿一般自由。这就是我反复大叫‘极乐! 极乐!’时，心里所想的。”
       
接着，注意到那件事的重要性，世尊当时说偈：“不再受激者，克服有与非有者，他已超越恐惧，有喜、无悲，天神看不见他。
 
《增支部.三集》―― 佛陀：“你觉得如何：假定一位家主或家主之子有一栋房子：山形屋顶、墙内外涂灰、门窗紧闭、无穿堂之风。在屋里，他有一张马鬃软榻：上铺一床长羊毛褥、一床白羊毛褥、一床锦绣被、一床卡达里鹿皮毯，顶垂华盖、侧堆红枕。点一盏灯，四个妻子百般妩媚，伺候着他。他是否能自在安眠？或者你认为如何？

 

阿罗毗的赫塔迦：“是，世尊，他能自在安眠。世上的自在安眠者当中，他便是一位。”“不过年轻人，你觉得如何: 那位家主或家主之子，是否有可能升起贪欲的身火或心火――受贪火的烧灼――他苦恼难眠？”“是，世尊。”“然而那些贪火――受其烧灼，那位家主或家主之子苦恼难眠――该贪欲已被如来弃绝、根除，如拔起的棕榈、生机已失、永不再生。因此，他自在安眠。”
       
“年轻人，你觉得如何: 那位家主或者家主之子，是否有可能升起嗔怒的身火或心火――受怒火的烧灼――他苦恼难眠？”“是，世尊。”“然而那些怒火――受其烧灼，那位家主或家主之子苦恼难眠――该嗔怒已被如来弃绝、根除，如拔起的棕榈、生机已失、永不再生。因此，他自在安眠。“年轻人，你觉得如何: 那位家主或家主之子，是否有可能升起痴迷的身火或心火――受痴火的烧灼――他苦恼难眠？”“是，世尊。”“然而那些痴火――受其烧灼，那位家主或家主之子苦恼难眠――该痴迷已被如来弃绝、根除，如拔起的棕榈、生机已失、永不再生。因此，他自在安眠。”
 
《增支部.三集》：常有常有自在安眠，婆罗门已彻底解脱；他不再粘着感官欲乐，无积取，心清凉。既已斩断一切缠缚，制服内心恐惧，平息了，他自在安眠，已达到心的寂止。凡夫皆有生、老、死，却厌弃受其苦者，那些事他不能自免。见有情受这些苦，假如我厌弃，便不适合以同样于他们的方式生活。持此心态，了解法，不再抓取――我克服了对健康、青春、生命的一切沈醉感，视出离为安稳。我的力量升起，解脱清晰可见。如今再不可能求取感官欲乐。已走上梵行之道，我不回头。                     
 
《增支部.四集》：“有此情形，一个人已弃绝对感官欲乐的贪爱、欲望、喜爱、渴爱、狂热、执取。接着他重病不起，在重病不起时，他不想：‘唉，我热爱的那些感官欲乐，就要离我而去了、我要被迫离开它们了！’他不会悲伤、不会苦恼，他不哭泣、捶胸、狂乱。这便是一个面临死亡时，对死亡不惧不怕的人。”
以上佛经皆出自汉译《巴利经藏》
