* 非思量分别之所能解，唯有实修亲证
  # 持续不断的努力，并常自问，能否更努力一点。
** 十份时间，一份阅读一份交流八分实修。 谨守身口意
1. 熟读成诵。博学多闻，有助宣说，对实证并非必需
   一段一段慢慢读 细细读 保持正念的读
   广闻博览 http://wiki.sutta.org/wiki/%E5%85%AB%E6%88%92
2. 戒
3. 观息 定
4. 内观 慧
戒，摧毁言行的不当；定，摧毁思想的不当；慧，摧毁潜在的不净。
** 独处。只有自己。慎独
** 三法印，四谛，八正道 十二因缘
   无常、苦、无我；   苦、集、灭、道。
   戒（正语、正业、正命）定（正精进、正念、正定）慧（正见、正思维）

   缘无明而有行，缘行而有识，缘识而生名色，缘名色而有六处，
   缘六处而有触，缘触而有受，缘受而生爱，缘爱所以取生。

   布施/乐于助人、持戒/严于律己、忍辱/不卑不亢、
   精进/谦虚勤奋、禅定/专注坚定、般若(智慧)/公平无私
   
   纪律和道德、耐心和毅力、专注与内观、慈悲和爱心
   注意知识、力量和智能的不同
   根器和业力，因缘，十二因缘？
   # 三十七道品：四圣谛、四正勤、四神足、五根、五力、七觉支、八正道。
*** 异议：任何事物都有两面性，有苦必有乐？
	矛盾无时不有，无处不在。
	乐？乐的产生、乐的消失、获取乐的方法
	有哪些让我们快乐的东西？
	好吃的，好看的，好听的，好闻的，好玩儿的，
	舒适的，凉爽的，温暖的，柔滑的，安全的，
	顺心的，如愿了，被赞赏，被接受，被认同，被关心，
	被需要，能助人，
	没有债，充实而不忙碌，
	有理想并为之奋斗，有信念，有能力，有钱，
	经过努力后的收获，
	有知己
	感恩，原谅，知足，诚实守信，专注，认真，努力，坚持，
	良师益友，同情心，学而时习之，布施，慈悲，放下，照顾好自己，
	解决问题，做想做的事，活在当下，笑，冥想，
	
	知足常乐 but 知足，何其难！
	# 能让自己快乐起来的人更能得到更多的快乐！ 为什么不快乐呢？要快乐。
	美味，音乐，歌舞，轻松，健康，
	舒爽，畅快，赞赏，顺心，信仰，
	如愿，敬畏，权力，财富，助人为乐，，，
	它们来时带着快乐满足，它们去时留下烦恼空虚

	需求层次理论； 满足需求就会快乐。
	五类：生理需求、安全需求、社交需求(爱和归属感)、尊重需求和自我实现需求。
	1. 呼吸、水、食物、睡眠、生理平衡(健康）、分泌、性。
	2. 人身安全、健康保障、资源所有性、财产所有性、道德保障、工作职位保障、家庭安全
	3. 友情、爱情、性亲密
	4. 自我尊重、信心、成就、对他人尊重、被他人尊重
	5. 道德、创造力、自觉性、问题解决能力、公正度、接受现实能力
	6. 自我超越
	衣食无忧、安全、
对于不同年龄段的人会有不同的看法：
小孩子会觉得：生活中最快乐的事就是每天不用写作业，无忧无虑的玩儿。
有糖果零食，有动画片
青少年则认为：作业量不用太多，可以有闲暇的时间用来搞自己喜欢并且感兴趣的事。
青年们认为：每天打游戏，出去旅游。
成年人则想着和自己心爱的女友环游世界是最快乐的事。
中年人认为：全家人一块儿在一起吃饭，睡觉，逛公园是最快乐的事。
老年人认为：自己的儿女能常回家看看，一起吃一个团圆饭则是最快乐的事。
总之，有一颗良好的心态，那才是最快乐的事~~~~	

* 一切都失去了光彩，失去了意义
  任何的安慰，各种鸡汤，都显得苍白乏力
  何时？
  幻象？真实？

  预期 憧憬 想象 幻想 | 现实 真实
  
极限法，最极端的情况，认清问题本质。
如，世界上所有人都让你觉得丑陋和讨厌，还有什么奋斗的动力吗？
你拥有全知全能的力量，一切都在你想要的瞬间实现，还有什么乐趣吗？
* 信
  佛陀做为心灵导师的成功程度，完全取决于他训练弟子的技巧。

经典中为礼敬佛陀而称他为“无上士调御丈夫”①，
要检验这句话的真实度，就必须去看他所指导的男女弟子的气度。
就如太阳的价值，不只在它本身的光明，同时也在它照亮世间的能力一样。
因此，佛陀作为心灵导师的光辉，不只是取决于他教法的清晰度，
更是在他能启发前来求皈依者与因材施教。缺少弟子团体见证它转化的力量，
“法”（Dhamma）将只是学说与严谨修持的包裹，徒有令人钦佩的清晰与精确的理智，
但都与活生生的人无关。“法”只有在接触生命，提升它的追随者，
经他们转化为智慧、慈悲与清净的典范时，“法”才会有生命。

* 上班地铁上想起一个话题
每一天如何过才是有价值的呢？ 有钱有名有闲有健康有声色犬马
人生天地之间，若白驹过隙，忽然而已 ―― 庄子《知北游》

 有没有价值，有个非常简单的标准：每天是不是快乐开心。 就可以判断。
 如果发现自己常常不高兴，甚至每天都不高兴，那就一定出问题了。
 快乐就好。
 话是这样说， 还是有许许多多人是苦苦的过着每分每秒，或是麻木的过着分分秒秒。
对酒当歌，人生几何？譬如朝露，去日苦多。
青青子衿，悠悠我心；何以解忧？唯有肚肠

 有没有想过自己的三年五年或十年的目标？
 那么人生的目标呢？
 几个非常明确的例子：
 佛教是证入涅，基督教是进入天国，马克思主义者是共产主义，秦始皇是统一六国，
 体育运动员是金牌（挑战极限，突破极限），一般人是“成功”：有名有钱有时间，有健康

 # 什么是有益的,有价值的,被圣人称赞的，能导向涅的
 另一层面，生物界一个共同的目标是繁衍后代，传宗接代。
 追逐和享受感官欲乐，

・ 人生应该如蜡烛一样,从顶燃到底,一直都是光明的.―― 萧楚女
・ 人只有献身于社会,才能找出那短暂而有风险的生命的意义.―― 爱因斯坦
・ 人生的价值,即以其人对于当代所做的工作为尺度.―― 徐玮 
・ 但愿每次回忆,对生活都不感到负疚 ―― 郭小川 
・ 你若要喜爱你自己的价值,你就得给世界创造价值.―― 歌德 
・ 人生不是一种享乐,而是一桩十分沉重的工作.―― 列夫 ・ 托尔斯泰 
・ 人生的价值,并不是用时间,而是用深度去衡量的.―― 列夫 ・ 托尔斯泰
生命中真正重要的不是你遭遇了什么，而是你记住了哪些事，又是如何铭记的。――马尔克斯《百年孤独》
一个人知道自己为什么而活，就可以忍受任何一种生活。―― 尼采

作者：罗鹏
链接：https://www.zhihu.com/question/20447176/answer/19587501
人生观，你想成为什么样的人？
人生观是你对自己这一生总体的期待，你觉得作为一个人，就应该这样这样这样。
比如你是想成为有钱人，过别人羡慕的富裕生活；
还是想成为高官，用权力来服务人民(也可能是为了赚钱)；
还是想成为一个旅行者，去体验世界的精彩；
还是想成为一个老师，教书育人；
还是想成为一个有思想的人，有智慧的人，不让自己活得糊涂；
还是就想做一个普通人，有车有房，安稳的过日子......

价值观，对你来说什么更重要？人在做决定的时候，都会依靠内心的一套价值体系，
选择一个相对而言更值得的去做。
在你的这个价值体系里面，借钱的时候金钱更重要还是朋友更重要，
找女朋友的时候外表更重要还是品行更重要，跳槽时薪水更重要还是平台发展更重要，
周末享受生活更重要还是为事业学习更重要......

世界观，世界是什么样的？整体来说，世界观是庞杂的、模糊的。
但这不重要，重要的是要认识到世界是客观的，
我们中的大部分人都习惯于带着成见去看待现实世界，并把偏见强加于自己的现实观。
我们学会了依靠观念来理解现实（而不是通过观察），去假定现状与我们观念中预想的相似，
这比自己亲眼观察现状要来得方便。
举个例子，我个人认为世界是由需求驱动的，你是个什么样的人不重要，
重要的是你能满足别人什么需求。

最后强调一点，人生观、价值观、世界观是不断变化的，根据你的知识结构、
主观意识的改变而改变，这也是一个再正常不过的过程，永远没有极致。


任何一件事情，只要心甘情愿，总是能够变得简单。 ――安妮宝贝《彼岸花》

所有的大人都曾经是小孩，虽然，只有少数的人记得。
令她反感的，远不是世界的丑陋，而是这个世界所戴的漂亮面具。
每个圣人都有不可告人的过去，每个罪人都有洁白无瑕的未来。

这是一个最好的时代，这是一个最坏的时代； 
这是一个智慧的年代，这是一个愚蠢的年代； 
这是一个光明的季节，这是一个黑暗的季节； 
这是希望之春，这是失望之冬； 
人们面前应有尽有，人们面前一无所有； 
人们正踏上天堂之路，人们正走向地狱之门。
  ―― 狄更斯《双城记》

井蛙不可以语于海者，拘于虚也；夏虫不可以语于冰者，笃于时也；曲士不可以语于道者，束于教也。
――庄子《秋水》
从来没有人读书，只有人在书中读自己，发现自己或检查自己。 ―― 罗曼・罗兰

* 障碍 束缚 结使

这些难关便是：

贫穷时，布施助人难
富贵时，学习佛法难
舍弃自己的性命难
能够听经学佛难
生在佛法在世的时代难
控制自己的感情欲望难
遇到珍贵东西不奢求难
被侮辱不嗔恨难
有权势不居高难
与外境接触不动心难
广泛学习博览群书难
消灭自我的傲慢难
不轻视不懂学法的人难
对万物持平等心难
不说是非对错难
遇到大德善知识难
明心见性地学习难
随缘教化他人难
遇到境界并不为所动难
明白方便法以教化众生难

这二十难，我们需要记在心里，作为对境，时时自省吾身......

* 思
贪求、执取
预期 憧憬 想象 幻想 | 现实 真实

最小化，能不做就不做；最大化，力所能及的多做。 转变，时间如何度过？

获取关注 认同 或敬畏。喂养六条饿狼，眼耳鼻舌身意，六欲

最终的大boss - 性

存在感 我见 是怎么产生的？

学深刻地体验到真正的空无自性，是极大的喜悦，此时心变得无所执取，并且清澈而明亮。
如何验证？ 找到最“在意”的，丢弃它会怎样？ 比如，删掉收藏的图片视频文章好友等等
如何检验？ 若有良田千顷，家奴无数，富贵荣华，会否舍弃一切，清修悟道？

昏沉 散乱 邪淫 难戒 如之奈何？ 如何做？ 熟读成诵，如健身一样奋力锻炼心力
平静平稳、警觉专注、非常的警觉非常的专注、十分的警觉十分的专注

休息，而不是放弃

忽然想到一个游戏， 如果人和人交往的时候，完全诚实， 会是一种什么状况？

勿顾虑别人的过失，也勿顾虑别人有否作善或作恶；只须留心自己的过失，以及留心自己有否作善或作恶。
常思己过，莫论他非。

兴高采烈  欢欣鼓舞； 无精打采 百无聊赖

* 闻
http://www.nibbana.cn/
http://www.dhammarain.org.tw/magazine/new/dhammarain-mag-004.html
http://www.dhammarain.org.tw/
http://www.dhammarain.org.tw/magazine/rainall.html
http://www.hhfg.org/xxsz/f247.html

   本书是一部心灵之旅，它带领你参访许多佛法的系统和师父。
表面上，他们也许各有不同，甚至彼此矛盾，
然而，我们无须相互比较，评定优劣。
这些言语和系统底下都是唯一真理的不同展现。
法是不变的，正如草叶的低垂和云朵的飘动显示有风的存在，
大师们的文字和教诲也都指向相同的体验、相同的真理。

大唐西域记，瑜伽师地论，成唯识论

本书最有效的使用方式，是依照它们最初的写法，
即为了激励与薰陶心灵的目的而阅读；不应存着阅读小说的心态来读。
在此建议读者，一天最好不要阅读超过一章，
应该和你正在学习的某个特殊弟子“交朋友”，
思维他或她的生命与教导，并试着发现那些故事对现代人有何启发。
最快也要等到隔天，才可以进行下一章。
你的心可能会迷恋这些事，因此最好克制一下好奇心，
并不断提醒自己为何阅读这本合集的原因。


沙利子是个名副其实的真实朋友，他了解如何做对别人最有利，
像佛陀所描述的理想朋友一样，直言不讳地指出朋友的过错，毫不迟疑。
就是透过这种诚实的批评，他帮助阿奴卢塔尊者突破最后关卡，证得阿拉汉果，
如《增支部》的记载：

有一次阿奴卢塔去看沙利子，相互寒暄之后，他便坐下来对沙利子说：
“沙利子吾友，我以超越世人眼界的清净天眼，可以看见大千世界。
我精进不懈，正念、正知且无疑惑；我的身体平静无忧扰，我的心专注于一处。
然而，我的心却仍未从烦恼与贪着中解脱。”
“阿奴卢塔吾友，”沙利子说，“当你想到你的天眼时，慢心就生起了；
当你想到自己坚定的精进、正念、无忧扰的色身与专注一处的心时，掉举就产生了；
当你想到你的心不能从烦恼解脱时，这就是恶作。如果你能舍弃这三种心境，
不再注意它们，这将会对你有所助益，就能将心引导到‘不死界’。”

阿奴卢塔遵从沙利子的建议，很快便断除烦恼。


现实中很多人把爱情理想化，缺乏现实感，总希望自己的爱情像小说电视剧那般浪漫：
月白风清，白马王子突然从天而降；一见钟情，爱情之花突然奇迹般地大放光彩


法喻舟者
佛陀说教的并不是什么学说和哲理，它不是理论的推断或思考上的假想，它是实证经验的结果。
佛陀说所有一切都无常，都无分别的自体，这些都是佛陀亲证。
佛陀的目的并不是要解释宇宙，而是要帮助 带领 教导人们直接体验实相。
文字语言不能解释实相，只有亲身的体验才可使我们看到实相的真面目。
佛陀所教的是体验实相的方法，而不是实相本身。就如 渡河的木筏，指向月亮的手指。

简单生活：修习呼吸、静坐、留心专注地工作和遵守五戒。


十六观息法门
吸入气息时，知道自己在吸入气息； 呼出气息时，知道自己在呼出气息；
第一口气息：吸入长的气息时，要知道自己在吸入长的气息；呼出长的气息时，要知道自己在呼出长的气息。
第二口气息：吸入短的气息时，要知道自己在吸入短的气息；呼出短的气息时，要知道自己在呼出短的气息。
气息粗重时，知道气息粗重； 气息轻细时，知道气息轻细。
这两口气息帮助打断昏沉和妄念

第三口气息：吸入气息时，要觉观全身；呼出气息时，也要觉观全身。
这口气息能使你因观想身体而与自己的身体真正接触
第四口气息：告诉自己吸入气息会令身体安静平和，呼出气息时也告诉自己呼出气息会令身体安静平和
这口气息能帮助你获得身体上的平静祥和，因而达到心、身、气都合一

第五口气息：告诉自己吸入气息时感到喜悦，呼出气息时也告诉自己呼出气息时感到喜悦
第六口气息：告诉自己吸入气息时感到快乐，告诉自己呼出气息时感到快乐
这两口气息，能带你跨进感受的领域，替你创造滋养身心的平和喜悦，替你带来悦意的感受

第七口气息：吸入气息时，要觉观自己心内的活动，呼出气息时也要觉观自己心内的活动
第八口气息：告诉自己吸入气息时，自己把心内的活动平静下来，告诉自己呼出气息时，自己也把心内的活动平静下来
这两口气息能使你深入体会自己生起的感受，无论是悦意、不悦意或中立的，继而让你把它们平伏安稳下来。

第九口气息：告诉自己吸入气息时，同时觉观自己的心念；呼出气息时也同时觉观自己的心念
第十口气息：告诉自己吸入气息时，同时使自己的心念轻快平和，呼出气息时，也同时使自己的心念轻快平和
第十一口气息：告诉自己吸入气息时，同时在集中自己的心念，呼出气息时也同时集中自己的心念
第十二口气息：告诉自己吸入气息时，同时释放自己的心念，呼出气息时也同时释放自己的心念
这四口气息带你跨进第三个领域--心。

第十三口气息：告诉自己吸入气息时，同时观照万法的无常性体，呼出气息时也同时观照万法的无常性体
第十四口气息：告诉自己吸入气息时，同时观照万法的坏灭，呼出气息时也同时观照万法的坏灭
第十五口气息：告诉自己吸入气息时，同时观想解脱，呼出气息时也同时观想解脱
第十六口气息：告诉自己吸入气息时，同时观想舍离放下，呼出气息时也同时观想舍离放下。
这四口气息行者便可以进入心所产生的物象领域，而集中心念以观察万法的实相真性。

作者：明慢慢
链接：http://www.jianshu.com/p/9edad874c0fc
碓矗杭蚴
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

应避免走入两个极端。
哪两个极端呢？一是纵情地追求感官欲乐，那是低劣、粗俗、粗鄙、卑贱与有害的。
另一个是施行各种自我折磨，那是痛苦、卑贱、与有害的。
如来所发现的中道远离这两个极端，它能带来见、知，并导向寂静、证智、等觉、涅。
什么是中道呢？
即是八正道，也就是正见、正思维、正语、正业、正命、正精进、正念和正定。
# 戒（正语、正业、正命）定（正精进、正念、正定）慧（正见、正思维）

* 疑 疑问 疑虑 
疑虑：都出家，人类就消失了; 耕作者出家了，其他家人怎么办？
疑问：若无一个延续不断的灵魂，那么业报是如何运作的呢，承受者是谁呢？
无我与轮回的矛盾？

闻思修 戒定慧  信愿行 佛法僧
尘世是否有真正快乐的人？旅行，去寻找真正快乐的人？

* 修
所做的，所拥有的，能否使心灵更美好？身体更健康？赢得尊重？带来快乐？带来财富？
* 记录
  历程
2017-04-24 欲，是牢笼，是皮鞭，是诱饵，是火焰
欲，是囚禁灵魂的牢笼，是奴役身心的皮鞭
是蒙蔽智慧的巨幕

看到了障碍，还需要更加努力才能清除它；
看到了目标，若不努力前行也不能到达它。
看到了果实，若不去采摘亲尝，也不知其味。
2017-09-18
我:
心太衰弱了，即使用文字或图像来辅助，勉强维持行动的路线和方向，依然时常处于散乱状态。
我:
早睡早起，是性价比最高的自律
我:
心是那么孱弱，以至于天天灌鸡汤也不能抵御各种无聊的诱惑，
刷微信，刷微博，追剧，刷电视频道，游戏，，，
我:
身见，我执，紧张，分别计较
这个翻腾抓狂焦躁不安的心，想驱使你做什么呢!? No/Yes/Stop

常思己过，莫论他非。看看是否可以做到更好！
消除行为上的自私自利。
消除思想上的自私自利。
找到并消除自私自利的根源。可能性？
我:
谨守身口意，舍弃身体的娱乐，心理的娱乐，找到并断灭欲乐的根源
我:
不做任何享乐
我:
不做任何享乐，因为毫无价值，虚妄不实，隐伏过患。

贪恋 嗔恚 掉悔
掉悔：掉悔是指掉举与恶作。掉举是心的散乱，恶作是追悔已造之恶（或当行而未行之善），
因为两者都源于困扰的念头，皆有导致心、心所不宁静的作用，故合为掉悔盖。

一切不可执取，放松、放下，苦自然止息。
空虚，孤单，
脱离人群，脱离社会，脱离世俗，产生空虚感

2017-09-27 14:00:54 看好门, 谨守身口意。
  禁语，减少与人的交流，包括微博、朋友圈等各种形式的交流
  与人交流和交往的需求，谨慎把守

我们往往只看见得或只能看见失
而看不到因得而付出的代价，因舍而获得的财富

他很坦率、纯真，对事物不会执着于某些特定想法，
也没有一个自我可保护的妄见，因此，经常处于喜悦和安详之中。

佛法一再强调，禅修时，有所得之心会增强无明，
以为有什么可以获得，以及有一个可从这些力量受益的人。能受什么益呢？

智能是单纯的，它既不是知识也不是力量，o是跟眼前、当下的情境和谐无碍，既无所得，也无所失。

2017-10-11 13:47:58 欲壑难填！越放纵越不满足！
乐少，苦多，失望多，带有多少危险和祸患！
放纵、贪婪并不能使人满足，约束和节制反而更容易导致满足。

如何做到？觉知，放松，放下。
无明是贪嗔的根，时时观照，刻刻清醒，如此训练心，觉知越来越微细的感受

2017-10-13 17:34:09 此一分钟与彼一分钟，没有不同。不同的是此刻心情与彼时心情。

2017-10-16 13:52:25 火上浇油，釜底抽薪
欲望就是火，满足欲望就是往火上添柴，欲火更旺。

强颜欢笑。心有余力不足的感觉，想要的多于能做到的了，疲惫

『感官五欲是乐少、苦多、失望多、带有多少危险祸患』却不能舍离
但愿长醉不愿醒，世间写照啊

2017-10-17 17:11:28 觉醒者 醒觉之道。我们是浪花一朵朵

2017-10-26 言行举止，想想，是否被圣贤所支持、赞赏？
三次读诵：
皈依佛，此生修行大道的导师。
皈依法，它是了解与慈爱之道。
皈依僧，生活在和谐和觉察中的团体。

2017-10-27 09:16:34 未经训练的心？不安分，不持久，不满足，不清澈、不明亮、不平等；
  对不喜欢的感受，忽视、歪曲、压抑、抗拒、嗔恚
  对于喜欢的感受，贪求、执取
  应平等对待，接受，看清，看透，舍离，不受其缠缚，黏着。

简单生活：修习呼吸、静坐、留心专注地工作和遵守五戒。

2017-10-30 09:05:38 独处！此时与彼时，并无区别。
  对于喜欢的，心会升起贪求、执取、追逐、幻想，产生快乐，而后忧虑
  对不喜欢的，心会对其压抑、抗拒、忽视、歪曲，产生烦恼，乃至愤怒
  若有平等心，直面、接受、看清、看透、舍离，不受其缠缚，黏着。
生老病死，愁悲忧恼，怨憎会，爱别离，求不得
忧，悲，愁，悔，恼。
2017-11-07 08:53:31 一切教说，只为一个目的，离执离贪，得心解脱
# 若达到目的也只由一个原因――精进实修。
人云亦云，没有自己；
大多数人被困于常识、知识、传统、自己的见解、理论和经验中，
差别只在包含错误的多少，并无高下。

* 读书，并非百利无害
  非圣书，屏勿视，蔽聪明，坏心志。
  过犹不及，不要花费太多时间读书。
  万般皆下品惟有读书高，警惕这种优越感。
  纸上谈兵，变成书呆子。尽信书则不如无书。
  读书使人明智，但明智的后果未必是带来快乐。

* 其他
  黑猫白猫，抓到老鼠就行； 发展才是硬道理。
  问题：为啥抓老鼠？为啥发展？有何代价？有啥局限性？

** 辩证法的三大规律、五大范畴、三个基本观点
*** 辩证法三大规律
即对立统一规律、质量互变规律、否定之否定规律。这三大规律在哲学上普遍性达到极限程度。
这是黑格尔在《逻辑学》中首先阐述出来的，恩格斯则将它从《逻辑学》中总结和提炼出来，从而使辩证法的规律变得更加清晰了。

辩证法规律揭示的全是极限本质之间的联系，是抽象程度最高的产物。
尽管辩证法的规律都是从概念的推演中抽象出来的，
但是这些规律完全与客观现实的本质运动相一致，因此它们都是具有极限真理的客观规律。　　

辩证法的三大规律彼此之间的联系是一分为二的关系。
基本规律是对立统一规律，它是其中的“一”。量变质变规律与肯定否定规律是“二”。　　

用逻辑关系图表示，是这样的形式：　　
对立统一规律┤ （核心规律）
┌量变质变规律――变化规律：内部变化规律　　
└肯定否定规律――发展规律：外部过程规律　　

否定之否定规律包含在肯定否定规律内部，属于发展的连续性具有的客观规律。　　
从哥德巴赫猜想的哲学证明中我们看到，对立统一规律表现得最突出，其次是量变质变规律。
否定之否定规律存在不存在呢？我们说，这个规律在哲学证明中也体现出来了，但是很不明显。

对立统一规律
对立统一规律即事物的矛盾规律，揭示了事物联系的根本内容和发展的动力，是唯物辩证法的实质和核心。
质量互变规律
事物的质、量、度。任何事物都具有质和量这两种规定性。质是指一事物区别于它事物的内部的规定性。
量是指事物存在和发展的规律。一定的事物都具有一定的质和一定的量。是质和量的统一体。
？质与事物是直接同一的，一定的质就是一定的事物。质是人们区分、认识具体事物的客观依据。
量与事物不是直接同一的。事物在一定范围内量的变化，只要不引起质的变化，一事物仍保持其质的稳定性，仍是原来的事物。
这种保持事物质的数量界限就是度。度是质和量的统一。

否定之否定规律
否定之否定规律.肯定―否定―否定之否定，是事物矛盾运动的进一步展开，它所提示的是事物发展的道路和总趋势。
1、事物的肯定方面和否定方面。肯定方面是指保持事物自身存在和性质稳定的方面；否定方面则是事物否定自身存在，促使事物质变走向死亡的方面。肯定方面和否定方面是事物内部固有的相互依存、相互排斥的两个方面。任何事物都是肯定和否定这两个方面的矛盾统一体。
2、辩证的否定。（1）辩证的否定是事物的自身否定。由于事物自身所固有的肯定因素和否定因素的对立统一，当事物的肯定方面占主导地位时，事物保持自身质的稳定性，处于量变阶段，而当矛盾双方长期斗争，否定方面战胜肯定方面而居于支配地位时，发生矛盾转化，量变也转化为质变，以致该事物死亡，发展为新事物。（2）辩证的否定是事物发展和联系的环节：①否定是事物发展的决定性环节。事物的发展是旧事物死亡和新事物产生，是质变；发展只能通过否定旧事物才能实现。任何新事物都是在否定旧事物的基础上产生和发展起来的；没有否定，就没有旧事物的死亡和新事物的诞生，也就没有发展。②否定是事物联系的环节。否定是新事物代替旧事物，新旧事物有着本质的区别。但是，新事物是从旧事物的结体中脱胎出来的，是在旧事物的基础上发展起来的。新旧事物之间的这种内在的、必然的联系，正是通过否定这个环节实现的，表现出事物发展过程中连续性的特征。
3、否定之否定。事物运动全过程的辩证图景是：肯定――否定――否定之否定，是经过两次否定，三个阶段的周期性过程。只有全部走完这个周期性过程，才能达到矛盾的完全解决。并使新事物日益完善，这是否定之否定，“仿佛回到原来出发点”的辩证发展的真谛。
4、事物发展是前进性与曲折性的统一。否定之否定规律表明，事物发展方向和总趋势是前进的，上升的，而事物发展的道路则是曲折的。事物发展是前进性和曲折性的统一。事物发展的方向是前进的，上升的。因为事物发展过程中的每一次否定都是消极因素的服从和积极因素的保留，是一个新陈代谢的日益完善的过程。因此，事物发展从低级到高级，呈现出前进与上升的趋势。事物发展的道路是曲折的。曲折性主要表现为：第一，事物经过两次否定，出现第一个阶段的某些特征。仿佛是向旧事物的某种回归，使事物发展道路不是呈直线型，而是呈“之”字型。第二，事物发展过程中会出现暂时的挫折，甚至发生暂时的倒退或逆转。？否定之否定规律所揭示的事物发展的前进性和曲折性，说明新陈代谢是宇宙间不可抗拒的规律。符合客观规律，具有强大生命力的新生事物是不可战胜的。尽管道路曲折险阻，但只要是真正的新生事物，总是能战胜各种消极因素，克服阻力，茁壮成长。

*** 唯物辩证法的基本范畴（五大范畴）
1、现象和本质。（1）现象和本质是揭示客观事物的外在联系和内在联系相互关系的一对范畴。现象是事物的外部联系和表现特征。现象中分真象和假象，真象是从正面表现本质的现象，假象是从反而歪曲表现本质的现象。本质是事物的根本性质，是组成事物基本要素的内在联系（2）现象和本质的辩证关系。①现象和本质的对立和区别是：现象是事物的外部表现，人们的感官可以直接感知；本质在事物的内部，只能通过抽象思维去把握。现象是个别、片面的东西；本质是一类现象中一般的、共同的东西。现象多变、易逝，比本质丰富、生动；本质则相对稳定，比现象单纯、深刻。②现象与本质又是统一的。一方面，本质离不开现象，任何本质都要通过一定的现象表现出来，不表现为一定现象的纯粹本质是不存在的；另一方面，现象也不能脱离本质，本质决定现象，即使是同本质鲜明对立的假象，也为本质所决定，也是本质的一种表现。③现象和本质辩证关系原理的意义。①现象和本质的对立，说明了科学研究的必要性；现象和本质的统一决定了科学研究的可能性。科学的任务就是通过现象去认识本质，达到科学的认识。②在实际工作中，要注意把现象作为入门的向导，透过现象去认识本质，不要为假象所迷惑。
2、原因和结果。原因是指引起一定现象的现象。结果是指由原因的作用而引起的现象。在现实世界中原因总是伴随着结果，结果一定是由一定原因引起的；因果双方失去一方，另一方也就存在。同时，在无限发展的链条中每一现象发展的原因和结果往往是相互作用，互为因果的，即甲现象引起乙现象，反过来乙现象又作用于甲现象，甲乙互为因果，即因果循环。？承认因果联系的客观普遍性是进行科学研究、获得科学认识的前提。科学研究在一定意义上，就是揭示事物因果联系，从而提出解决问题的方法。正确地把握因果联系，有利于总结实际工作经验。总结工作经验时，不仅要肯定成绩，发现错误，而且要找出取得成绩和产生错误的原因，这样，才能不断推动工作。准确地把握因果联系，能增强工作中的预见性。预见今后工作中可能产生的成果，及时采取措施，防止和排除不利成果，是做好一切工作的重要条件。
3、内容和形式。内容和形式是提示事物内在要素和结构及其表现形式之间关系的一对范畴。（1）内容和形式之间的辩证关系。①内容是指事物的内在要素及其相互之间的关系，主要包括事物的构成成分、内在特征、运动过程以及发展趋势。形式是指事物各要素之间的结构及其表现方式。内容活跃易变，形式则相对稳定，内容不同于形式。②内容决定形式，形式对内容有反作用，由此形成内容和形式之间的矛盾运动，不断地使形式与内容之间由相对适合到相对不适合再相对适合的发展。（2）掌握内容和形式辩证关系的原理具有重要意义。①注重内容，善于选择合适的形式。②根据内容与形式矛盾运动的原理，推动事物的发展。
4、必然性和偶然性。必然性是指客观事物联系和发展过程中合乎规律的、一定要发生的、确定不移的趋势。偶然性是指客观事物联系和发展过程中并非确定发生的，可以这样出现，也可以那样出现的不确定的趋势。（1）必然性和偶然性是对立的。①必然性和偶然性在事物发展中所处的地位和所起的作用不同。必然性是事物发展中居支配地位，决定事物的发展方向；偶然性居于次要地位，不决定事物的发展方向。②必然性和偶然性体现事物发展的两种不同趋势。必然性是事物发展中持久稳定的趋势；偶然性则是暂时的、不稳定的趋势。2）必然性和偶然性又是统一的。①必然性存在于偶然性之中，没有脱离偶然性的粉粹的必然性。必然性通过大量的偶然性表现出来，并为自己开辟道路。②偶然性体现必然性，并受制于必然性。没有脱离必然性的纯粹的偶然性。偶然性是必然性的表现形式和补充，凡是存在偶然性的地方，其背后总是隐藏着必然性。任何偶然性都不能完全地、绝对地摆脱必然性的支配和制约。③必然性和偶然性在一定条件下可以相互转化。由于事物范围极其广大和发展的无限性，必然性和偶然性的区分是相对的。在一定条件下，偶然性可以转化为必然性，必然性也可以转化为偶然性。（3）必然性和偶然性辩证关系原理的意义。①掌握客观必然性是科学认识和实践的基础。只有立足于必然性，努力研究揭示必然性，才能使科学研究沿着正确的方向发展。只有认识必然性利用必然性才能获得自由。②在科学研究中偶然性的作用也不能忽视。只有认识偶然性在事物发展中的作用，才能注意利用一切的偶然因素去推动科学发展，防止和消除不利的偶然因素的影响，做到“有备无患”。
5、可能性和现实性。可能性是指包含在事物中的，并预示事物发展前途的种种趋势，是潜在的，尚未实现的东西。现实性是指导包含内在的根据的，合乎必然性的存在，是客观事物和现象种种联系的综合。（1）可能性和现实性的辩证关系。①可能性和现实性是相互区别的，可能性是尚未实现的东西，不是现实性；而现实性则是已经实现了的可能性，已不再是可能性。②可能性和现实性又是统一的，它们相互依赖、相互转化。相互依赖。可能性存在在于现实性中，离开现实性，就谈不上可能性；现实性也离不开可能性；没有可能的东西，不会成为现实，任何现实都是由可能转化来的。？相互转化。可能性在一定条件下转化为现实性；现实性又产生新的可能性，即现实性化为可能性。事物的发展过程是一个不断由可能向现实转化的赛程。这种转化需要一定的条件。在人类社会实践中，可能由现实转化需要客观条件，还需要主观条件。（2）可能性和现实性辩证关系原理的意义。①我们的一切工作必须立足于现实，从现实出发制订我们的方针、方案、计划。只有从现实出发，才能正确分析种种可能性，正确预见未来，使主观能动性的发挥建立在可靠的基础上。②在制订计划、方案前要注意分析可能性的各种情况：可能和不可能；现实可能和非（抽象）可能；好的可能和坏的可能；可能性在量上的大小，即或然率。我们要发挥主观能动性，争取好的可能性转化为现实，避免坏的可能性转化为现实，从最好处努力，从最坏处准备，使自己处于主动地位。③可能向现实转化了客观条件，还需要主观件，即主观努力。我们要发挥主观能动性，创造各种条件，使好的可能性向现实性转化。一、以实践为基础的能动反映论⑴唯物主义坚持物质第一性，意识第二性，主张认识是对客观物质的反映。⑵马克思主义将实践的观点引入认识论，消除了旧唯物主义脱离社会实践的消极直观性的缺陷，科学地说明了实践是认识的基础，认识的主体和客体都是在实践中生成和发展的，认识不再是对客体的消极直观反映，而是对客体的能动反映。⑶马克思主义认识论将辩证法贯彻于认识过程，阐明了认识是一个充满矛盾运动的过程，是一个随意实践的发展由浅入深，由低级到高级的永无止境的辩证发展过程，从而消除了旧唯物主义反映论的僵化不变的形而上学缺陷。⑷在马克思主义认识论中，实践的观点是第一的和基本的观点。

# 七大范畴：原因与结果、必然与偶然、可能与现实、内容与形式、现象与本质、系统与要素(整体与部分)、结果与功能

现象与本质的辩证关系
（一）现象和本质是对立的。现象和本质有明显的差别。现象是事物的外在方面，是表面的、多变的、丰富多彩的；本质是事物的内在方面，是深藏的、相对稳定的、比较深刻、单纯的。因而现象是可以直接认识的，本质则只能间接地被认识。
（二）现象和本质是统一的。
1、两者是相互依存的。现象是本质的现象，本质是现象的本质。也就是说，本质只能通过现象表现出来，现象只能是本质的显现，他们之间是表现和被表现的关系。任何一方离开了另一方都是不能存在的，实际的存在总是现象与本质的对立统一。
2、两者是相互蕴涵的，在实际上也是相互包含的。本质寓于现象之中，这是非常明显的，因为现象是整体，本质是现象的一部分，固然是根本性的部分。反过来，本质也包含现象，因为现象尽管是多种多样的、纷繁复杂的，但毕竟是由本质决定的，早已潜在地包含于本质之中。
3、现象与本质是可以相互转化的。本质变现象应理解为本质表现为现象。某一具体的人无疑是本质与现象的统一体，但其本质也在不断地表现出来，即不断转变为现象。现象与本质的相互转化，正是感性认识与理性认识相互转化的客观基础。
（三）区别真象与假象、假象与错觉
真象是从正面表现本质的现象。假象则是一种虚假的现象，它也是本质的一种表现，但却是本质在特定条件下的一种反面表现。
错觉是由于人的感觉上的错误造成的，属于主观的范畴；假象则是由客观存在的种种条件造成的，它是现象的一种，属于客观的范畴。
现象和本质这对范畴作为思维形式，具有重要的方法论意义
（一）现象和本质的对立，说明了科学研究的必要性；现象和本质的统一，决定了科学研究的可能性。
科学研究的任务就是通过现象去认识本质。人们只有通过对大量现象的研究，才能发现事物的本质，达到科学的认识。如果二者只有对立而无统一，那么一切科学研究、科学认识就是徒劳无益、白费力气的了。
（二）在实践中要注意把现象作为入门的向导，通过现象去认识事物的本质。
从现象进入本质是认识的深化，却不是认识的终止。由现象进入到本质，在一定程度上认识到了事物的规律性以后，还必须在这种认识的知道下，继续地研究尚未研究过或尚未深入研究的现象，以此补充、丰富和加深对于事物本质的认识。这是一个有现象到本质又由本质到现象的循环往复的认识过程。
（三）注意防止经验主义和理性主义（教条主义）的出现
哲学史上的经验主义和理性主义是自觉的思想体系，以割裂现象与本质为其立论的依据。经验主义否定感性认识到理性认识的转化，也就是否定现象到本质的转化；理性主义否定理性认识到感性认识的转化，也就是否定本质到现象的转化。实际生活中的经验主义和教条主义并无自觉的思想体系，它们只是表现为实际认识过程中的片面性，但其认识基础同样是割裂现象与本质的辩证统一。

*** 三个基本观点
唯物辩证法是关于联系和发展的科学，联系的观点和发展的观点是它的总特征，辩证法的三大规律都是讲发展的，五大范畴都是讲联系的。
联系的观点：物质世界是一个普遍联系的统一整体。联系是指事物内部要素之间和事物之间的相互影响、相互依赖、相互作用。联系是客观的、普遍的，联系的形式是多种多样的。
发展的观点：物质世界是不断发展的世界，运动是宇宙间一切的存在方式。发展是指事物由简单到复杂、由低级到高级的运动过程，它的实质是新事物的产生和旧事物的灭亡，发展是客观的，有规律的。
一分为二的观点：唯物辩证法主张全面地看待事物，既要看到普遍联系，又要承认它们之间的区别，既要看到事物运动的绝对性，又要承认事物的相对静止，既要看到事物的正面又要看到事物的反面，既要看到个别，又要看到一般。

*** 能否找找辩证法的问题，或局限，或适用范围？
辩证法是一件思维利器。
也仅仅是一件利器而已。
** <辩证法的适用范围> 辩证法的局限性
　　真理永远属于少数人，这是不变的真理。所有辩证法思想家认为辩证法是表达精神真理的必然形式而放弃了真理的真实内容，
使其成为纯粹逻辑方法，导致与真理整体本身无缘的结果。生活中每个人都可以使用辩证逻辑看问题，但这种方法也同样使每个人都丧失了亲历真理的能力或机会。
最终大家都丧失了创新、以及自身独立发展的潜在素质。虽然人们可以都说同样的话语，都做同样的事情，但是智慧、真理却与大家无缘了。

　　我们认为，辩证法与西方传统形而上学各有一定的适用范围，在一定程度上都具有真理性。但我们的思维能力决不局限于此，还要继续前进。　

　　我们不能满足辨证理性的机械性、强制性、非实存性和纯粹形式化。因为一切生活逻辑都是有实质内容的真理化表达，是赋有生命力的活的逻辑。

*** “非黑即白”的二分法，0和1，造就了非此即彼的对立局面。
*** “缺乏对精神领域的部分”
	# 问：按照唯物辩证法，人生的意义是什么？享乐？奉献？共产主义？
普遍的社会公德风尚不能形成。社会人心涣散，或者集体无意识盲从。
客观化方法的局限性。辩证理性因为其纯粹客观化、规律化、逻辑化而成为一种科学方法的支持，
但它同时也丧失了人性、天道，人与人，人与自然，也就是人-世界关系是不可彻底调和的矛盾关系，
一切和解只能成为虚假的智力游戏和权宜之计。所以我们说辩证法不是人类智性的进化而是倒退，
虽然从形式上看它比简单的同一律有灵活性，似乎丰富了人类的认识世界的手段，
但根本上它是精神颓废的产物，是真正文明、科学、道德丧失的产物。


* 人物

** 赫拉克利特《论自然》残篇
“智慧只在于一件事，就是认识那善于驾驭一切的思想。”
“清醒的人们有着一个共同的世界，然而在睡梦中人人各有自己的世界。”

太阳每天都是新的。 
如果说幸福仅仅在于感官的快乐，那么，牛吃到草料时是最幸福的。 
驴子会选择饲草，而舍弃黄金。 

大多数人不反省自己遇见的事，
哪怕因此得到教训也还是没有真正地思考它，虽然他们自以为了解了。 

人们死后的遭遇，既不是人们所期待的，也不是人们所想像的。 
渊博的知识并不能使人变得有智慧。
不然，它早就已使赫西阿德，毕泰戈拉以及克塞诺芬尼和赫卡泰变得有智慧了。 

智慧只在于一件事，就是认识那驾驭万物的思想。 
灵魂的边界你是找不出来的，哪怕你走遍每一条大道也找不到，他的根源隐藏的特别深。 

我们有没有走过同一条河流。 
时间是一个玩色子的儿童，他掌握着一切。 
看不见的和谐比看得见的和谐更好。 

海水是最清洁的，又是最不清洁的：
对于鱼，它是能饮用的和有益的；
对于人，他是不能饮用的和有害的。

人物轶事编辑
朋友
作为藐视人者，他没有朋友。
他在晚年又隐居起来，只靠野菜和水维持生命，不和任何人往来。
敌人
赫拉克利特尽管出身高贵，有机会做高官，但他却从未接受过职位。
他是一个异类，当时的希腊人把他看成是一只珍稀动物：带着尊敬和惊奇的混合感情。
女人
赫拉克利特身边没有女人，平日也完全避免和女人接触，
在他的作品中也只是提到，女人始终处于和男人的斗争之中。这是很多斗争中的一个。
世界就是在这样一些斗争中产生的。
自己
赫拉克利特曾说过：“我研究了我自己。”
这就是说，他的认知并不是一个自然科学家的的事业（尽管他的书称为《论自然》），
而是一个把目光对准自己内心的人的事业。
由于他成功地排除了其他人的外部干扰，把自己封闭起来，他才有可能潜入到灵魂的深处。
那里的个性的区别已不存在，人与人越来越相似。那是一种人的本性真正存在的地方。
据说，他在隐居时，以草根和植物度日，得了水肿病。
他到城里找医生，用哑谜的方式询问医生能否使阴雨天变得干燥起来。
医生不懂他的意思。他跑到牛圈里，想用牛粪的热力把身体里的水吸出，结果无济于事，
去世时大约60岁。

* 7种让人越来越蠢的认知偏差
  https://www.zhihu.com/question/37723905
https://mp.weixin.qq.com/s?__biz=MjM5NTU0NTYxNA==&mid=2652647409&idx=1&sn=f6b0a9b701b85eb2bec60f6b0c23714f&chksm=bd1e58908a69d186407cf8096a546c5d65f297d45d283e816617e176ff97b619b9196bd32410&mpshare=1&scene=1&srcid=08103CGa3dZ4da8oAKjT2bzG#rd
1.自利归因偏差(self-serving bias）
成功时，觉得多半是自己的功劳；失败时，甩锅给别人或外界环境。
# 对治：常思己过，莫论他非

2.行动者-观察者偏差(actor-observer effect)
我们观察别人的行为时，倾向于指责别人的人品，而忽视情境的影响。
人在矮檐下，怎能不低头
# 对治：设身处地，换位思考

3.错误定价（misvaluation hypothesis）
你对一件事的定价，就是你认为，这件事带给你的价值。
之所以会有错误定价偏差，是因为很多人，只定价了一件事的短期价值。
例，明明知道电子游戏，休闲时玩一玩即可，可很多人心中，游戏的「定价」奇高，因为追求即时的愉悦感，他们打游戏茶饭不思。
读书学习，短期看不到价值，他们便放弃；游戏，短期获得了快感，就拼了命地玩。
# 对治：？

4.过度自信偏差（overconfidence theory）
如果你正确定价了读书，明白读书的重要了……还可能陷入另一种偏差。
比如「今年我一定要读100本书！」，或者朋友圈集赞「你们给我点几个赞，今年我就要读几本书！」。
心理学家把人的这种迷之自信，叫做过度自信偏差。
# 对治：看看自己的前半生，做个简单的计划，行动吧

5.沉没成本效应(sunk cost effects)
上高中那会，共享车还没出世，有时早上起迟了，准备打的却苦苦等不到，反倒是公交车过去好几辆，我却还是想打的，
心想：“我都等了这么久的的士，得继续等下去，要不然先前花的时间不白费了？”

我的做法其实是很蠢的，这是典型的沉没成本效应。
等的士花的时间，就是我不可挽回的成本，却影响了我的决策，宁愿继续等下去也不愿坐公交……

谈恋爱时也一样，对方毅然决然提分手，你心想：“都谈一年了，付出了那么多，怎能轻易结束？”
可……Ta已经不爱你了，挽留不成，却还是要死缠烂打。
这不是蠢，是什么？
过去的牺牲和付出，就让它过去吧，如果不能把过去的痛苦和牺牲留在身后，那和身居牢狱有什么区别？
# 对治：站在当下，往前看
6.后视偏差（hindsight bias）
事后诸葛亮，事前猪一样。
# 对治：事先做足准备工作；丑话说在前头
7.幸存者偏差（survivorship bias）
常常看见这样的报道： 从月薪3000逆袭估值30亿估值企业CEO，他有什么秘诀？
打开文章，通常先讲一个潘磕嫦的故事，然后总结出123条道理，告诉读者这就是秘诀……
心理学家称之为幸存者偏差，千千万万个月薪3000的人里，只有他是「幸存者」，上了媒体报道，其他99.9%的人都「死了」。

大部分人只看到成功人士讲的大道理，却没看到背后的方法论、资源、家境、人脉甚至运气成分。
# 对治：

远离认知偏差，有这3个步骤：
1.改变你的元认知
认识到认知偏差的存在本身，就能削弱它的影响。

这个过程，其实调用你的元认知能力，即对思考过程的反思：
只有意识到思考过程中偏差的存在，才能去改变它，元认知为思考过程按下了停止键。

2.没错，你应该对号入座
认识到还不够，现实里的认知偏差往往很隐蔽，所以一定要联系你的现实经历。
比如：过去我犯过哪些偏差？将来，碰到同样的情况，才会想起来去避免。

3.慢下来，慢下来，慢下来
每天都能看到这样的标题：
几节课颠覆你的认知，几天教你把月薪提高十倍，几条秘诀教你成为高手……

无数的课程、文章，都号称能颠覆你的三观。
于是你心动了，点了购买，去感受「迅速」颠覆三观的感觉。

这个时代太「快」了。
它鼓动你迅速成功、鼓动你迅速购买、鼓动你迅速思考......

商家利用人性、利用心理陷阱、利用认知偏差，操纵你的钱包。
所以我建议你：在做任何决定前，给自己一些思考的时间，慢下来，慢下来，慢下来。

快，是时代病。
慢，是良药。

* 价值或意义
  难道人生的价值就是享乐吗？真实过程却是自讨苦吃，苦多乐少。
  难度人生的价值就是体验各种经历吗？有人一生都是重复那几件事

  人的生存只有两种：“美丽的活着”，亦或“为美丽的人活着”。――尼克 《东京食尸鬼》

如是思维，
看着男神女神的照片，能获得什么呢？能带来什么益处呢？
能让心灵更美好吗？能让身体更健康吗？能赢得尊重吗？还是能带来财富？
美是功利。
看到，触到，得到，拥有认为美的、吸引你的，从中能获得什么呢？能带来什么益处呢？
能让心灵更美好吗？能让身体更健康吗？能赢得尊重吗？还是能带来财富？

如此思维，你所做的，所拥有的，所渴求的，从中能获得什么呢？能带来什么益处呢？
能让心灵更美好吗？能让身体更健康吗？能赢得尊重吗？还是能带来财富？让生活更快乐？

看到美图，看到视频，看到完全符合自己心意的图片或照片，看到精彩细腻的故事文章，看到完全符合自己心意的实践视频，
从中能获得什么呢？某种感觉
这能带来什么益处吗？
能让心灵更美好吗？能让身体更健康吗？能赢得尊重吗？还是能带来财富？让生活更快乐？

看到，触到，得到，甚至拥有你认为美的、吸引你的东西或人，
从中能获得什么呢？还是某种感觉？更强烈一些的感觉？还有其他？
能带来什么益处呢？
能让心灵更美好吗？能让身体更健康吗？能赢得尊重吗？还是能带来财富？让生活更快乐？

心是欲的奴隶，身是心的马车。何曾有过片刻自由！
每个圣人都有不可告人的过去，每个罪人都有洁白无瑕的未来。
苦海无边回头是岸。愿一切众生，无敌意，无危险，无身体的痛苦，无心灵的痛苦。
戒，摧毁言行的不当；定，摧毁思想的不当；慧，摧毁潜在的不净。

《纪念白求恩》
我们大家要学习他毫无自私自利之心的精神。从这点出发，就可以变为大有利于人民的人。
一个人能力有大小，但只要有这点精神，就是一个高尚的人，一个纯粹的人，
一个有道德的人，一个脱离了低级趣味的人，一个有益于人民的人。

* 基督徒常常记住的30句话
１.一切在神手中，故你不要怕任何事临到你．

２.没有什么危险会比神离你更近．

３.在试炼中遇见神，比脱离试炼更好．

４.在任何地方你都能将挂虑变为祷告．

５.每一次试探都是你投靠神的机会.

６.无路可走的时候可以向上看．

７.苦难常是神给你最好的化装祝福．

８.敬畏神能使我们不惧怕人．

９.家庭有祭坛，使许多家庭改变．

10.平时与主日不同的人是假冒的人．

11.今世所造成的品格将带到永生．

12.当困难来找你时，你去找神．

13.跟随基督的人不会走错路．

14.讨神喜悦的人不一定人都喜欢．

15.将自己完全献身给神并不是冒险．

16.称神为父，却表现如孤儿，是不信神．

17.奉献给神不是损失，乃是最大的得着．

18.贪心使人有所得，但失去的比所得的更多．

19.与罪玩耍的，是在那里与审判做儿戏．

20.你要管束你自己，免得别人来管束你．

21.你原谅你的罪，你的罪将来不被原谅．

22.你在伤害别人的同时也伤害了你自己．

23.罪不是由你来判断，乃是由神来判断．

24.无人能守住隐秘，因神和天使都看见你．

25.多注意自己的过失，即可忘记别人的过失．

26.不知足使富人变穷，知足使穷人变富．

27.你不与世俗分开，世俗要将你与神分开．

28.没有什么罪是小的，因为罪都得罪了伟大的上帝．

29.罪的快乐只是一时，它带来的痛苦却是永远．

30.魔鬼来叩门时，请让耶稣去开门．

经上说：以别神代替耶和华的，他们的愁苦必加增（诗篇16:4）。
这句话并不是仅仅指着基督徒说的，而是指着所有人类说的。
以金钱权力为自己的神，必然会愁苦加增。
即使得到了这一切，在生命终结之时，又有什么盼望呢？
亚历山大大帝戎马一生，建立了地跨亚欧非的马其顿帝国，
但他在临终时却倍感伤心和空虚。
他下命令让众人抬着他的棺材出殡之时，在棺材旁边挖两个洞，
让他的两只手伸出来。借此让所有民众看一看，
即使是亚历山大，走的时候也是什么都带不走，一样两手空空。

在神眼里，财富的多少、地位的高低和是否成功完全是两码事。
神眼中的成功，乃是我们生命的得胜，是圣灵的律胜过了肉体的律，
是我们的心完全放在了神的旨意之中，稳行在高处。

生有时，死有时；栽种有时，拔出所栽种的也有时；
杀戮有时，医治有时；拆毁有时，建造有时；
哭有时，笑有时；哀恸有时，跳舞有时；
抛掷石头有时，堆聚石头有时；怀抱有时，不怀抱有时；
寻找有时，失落有时；保守有时，舍弃有时；
撕裂有时，缝补有时；静默有时，言语有时；
喜爱有时，恨恶有时；争战有时，和好有时。（传道书3:2～8）

耶稣说：“在世上你们有苦难；但你们可以放心，我已经胜了世界。”

爱是恒久忍耐，又有恩慈；(哥林多前书 13:4 和合本)
爱是不嫉妒；爱是不自夸，不张狂，
不做害羞的事，不求自己的益处，不轻易发怒，
不计算人的恶， 不喜欢不义，只喜欢真理；
凡事包容，凡事相信，凡事盼望，凡事忍耐。
爱是永不止息。
先知讲道之能终必归于无有；
说方言之能终必停止；
知识也终必归于无有。(哥林多前书 13:8 和合本)

* 欲乐的过患？
首先 从理智上看清各种欲望和快乐是无益而虚幻不实的；然后 拔除对欲乐的追逐根源。
纵是虚幻也是快乐，干嘛要去除呢？ 仍然需要先从理智上认清，带来的过患？？
# 要拔除它仅靠理智是办不到的。如之奈何？
戒定慧
戒，摧毁言行的不当；定，摧毁思想的不当；慧，摧毁潜在的不净。

# 辛勤工作，努力奋斗，追求理想，是否是为了满足身心的各种欲求呢？
若世上只剩你一个人，还会有辛勤工作，努力奋斗，追求理想吗？
或者所有人都让你觉得丑陋而讨厌，还会有辛勤工作，努力奋斗，追求理想吗？
或者此生无望遇不到一个令你欣赏喜欢的人，还会有辛勤工作，努力奋斗，追求理想吗？

问：我们能否充分感觉和享受事物，同时又保持平等心？
答：当然可以。生命是要来享受有益于善的事物。但是不可以对任何事物起执着。
你保持平等心和享受，那么当你失去它时你泰然微笑：
「我就知道它会离开的。它已经离开了。有什么大不了？」那么，你才是真正地在享受生命。
否则，你变得执着，而如果你失去它，你将卷入痛苦中。所以不要痛苦。要在每个情况下都快乐。

# 感官欲乐的过患
https://www.douban.com/note/173085216/
《小部.法句经》：纵使天上下起金币之雨，我们的感官之欲也不会满足。‘它们是苦，远非乐。’
了悟此意后智者知道，纵使在天界般的感官之娱里也无乐可得。他是正自觉者的弟子，以终结感官欲望为乐。
 
《中部.哺多利经》：“假定一只狗，为虚弱与饥饿所困，路过一座屠宰场，有个技熟的屠夫或其学徒，朝它扔一串骨――刮净、沾血、无肉。
你们觉得如何：那只狗，啃着那串骨――刮净、沾血、无肉――它的虚弱与饥饿可会消解？ ”
“世尊，不会的。为什么呢？因为那串骨被刮净、沾血、无肉。那只狗除了疲倦与恼怒，什么也得不到。”
“家主们，同样地，一位圣者的弟子如此思索：‘世尊把感官欲乐比作一串骨，苦多、绝望多、过患更多。’
以正明辨如实看清了这一点，他会避免来自多种因素、依赖多种因素的安宁，培养来自单一因素、依赖单一因素的安宁，
由此止息对世俗之诱的执取与维持，不着余迹。”
 
《中部.苦蕴大经》：“何为感官欲乐的诱惑？比丘们，感官欲乐有五条。哪五条？
藉眼识别之色――愉悦、可喜、迷人、可爱、增欲、诱人。藉耳识别之声……藉鼻识别之香……藉舌识别之味……
藉身识别之触――愉悦、可喜、迷人、可爱、增欲、诱人。
有赖于这五条感官欲乐而生的喜与乐，那便是感官欲乐的诱惑。

那么，何为感官欲乐的过患？有此情形，一位族姓子从业谋生――无论会计、算师、耕作、商贾、牧牛、箭手、国王随从，等等
――他面对冷、他面对热、受蚊蝇爬虫骚扰、风吹日晒、死于饥渴。”
“感官欲乐的这个过患，即时即地可见的这一堆苦，是以感官欲乐为由、以感官欲乐为源、以感官欲乐为因、只为了感官欲乐。
这位族姓子若这般辛苦操劳，却不得财富，他于是忧愁、悲痛、哀叹、捶胸、痛苦。我的工作徒劳无获、我的辛劳毫无结果！
因此，感官欲乐的这个过患，即时即地可见的这一堆苦，也以感官欲乐为因……
“这位族姓子若这般辛苦操劳，得了财富，他便经历守护之忧苦:
‘如何不让国王、盗贼抢走我的财物，如何不让它给火烧毁、给水冲走、给不孝子孙夺走?’
正当他守护、看护财物时，它却给国王、盗贼抢走、给火烧毁、给水冲走、给恨心子孙夺走了。
他于是忧愁、悲痛、哀叹、捶胸、痛苦。‘我的财物尽失去了!’ 
因此，感官欲乐的这个过患，即时即地可见的这一堆苦，也以感官欲乐为因……
       
“再者，正是以感官欲乐为由、以感官欲乐为源、以感官欲乐为因、只为了感官欲乐，
国王与国王相争、贵族与贵族相争、僧侣与僧侣相争、家主与家主相争、母与子相争、
子与母相争、父与子相争、子与父相争、兄弟与兄弟相争、兄弟与姊妹相争、姊妹与兄弟相争、
友与友相争。接着，他们在争执、争闹、争论时，以拳、以土块、以棒、或以刀相互攻击，
招致死亡或如死之痛。" 因此，感官欲乐的这个过患，即时即地可见的这一堆苦，也以感官欲乐为因……
# 冲冠一怒为红颜 人为财死鸟为食亡 天下熙熙皆为利来，天下攘攘皆为利往。

“再者，正是以感官欲乐为由、以感官欲乐为源、以感官欲乐为因、只为了感官欲乐，
人们执起剑盾、架起弓矢、聚为两阵、冲进战场，一时矢矛纷飞、剑光闪闪;
在那里他们为矢矛刺伤、被刀剑砍头，招致死亡与如死之痛。
因此，感官欲乐的这个过患，即时即地可见的这一堆苦，也以感官欲乐为因……
       
“再者，正是以感官欲乐为由、以感官欲乐为源、以感官欲乐为因、只为了感官欲乐，
人们执起剑盾、架起弓矢、冲击陡滑的堡垒，一时矢矛纷飞、剑光闪闪; 
在那里他们受沸牛粪泼撒、被重物砸扁、给刀剑砍头，招致死亡或如死之痛。
因此，感官欲乐的这个过患，即时即地可见的这一堆苦，也以感官欲乐为因……
       
“那么，何为感官欲乐的解脱？凡是平息对感官欲乐的贪爱、放弃对感官欲乐的贪爱，那便是感官欲乐的解脱。”
 
《中部.苦蕴大经》：“比丘们，何为形色之诱？假定有一位贵族、婆罗门、或家主阶级的少女，
十五六岁、不高亦不矮、不胖亦不瘦、不黑亦不白。她的美貌与魅力可是在最盛之时？”
“世尊，是的。”
“凡有赖于该美貌与魅力而升起的喜与乐：那便是形色之诱。
       
“那么，何为形色之诱的过患？有此情形，人们可能后来再见同一位女子八十、九十、百岁之相：
衰老、如橼木般弯曲、佝偻、持杖、抖索、衰弱、豁牙、白发、少发、秃发、皮皱、肢体多斑。
你们以为如何：是否她昔日的美貌魅力已然褪尽，过患显现？”
“世尊，是的。”
“比丘们，这便是形色之诱的过患。
       
“再者，人们可能再见同一位女子在病患、痛苦、重疾之中，卧于屎尿之污、靠他人抬起放下。
你们以为如何: 是否她昔日的美貌魅力已然褪尽，过患显现？”
“世尊，是的。”
“比丘们，这也是形色之诱的过患。

“再者，人们可能再见同一位女子弃尸坟场――一日、两日、三日，肿胀、青紫、腐烂。
你们以为如何: 是否她昔日的美貌魅力已然褪尽，过患显现？”
“世尊，是的。”
“比丘们，这也是形色之诱的过患。

“再者，人们可能再见同一位女子弃尸坟场，为乌鸦、鹰鹫、为狗、土狼等动物啄食……
骨胳尚有血肉、以筋相连……骨胳血肉尽失、以筋相连……
骨腱分离、散乱四处――此处手骨、彼处足骨、此处腓骨、彼处腿骨、此处臀骨、彼处椎骨、
此处肋骨、彼处胸骨、此处肩骨、彼处颈骨、此处腭骨、彼处齿牙、此处头骨……
骨色发白如螺壳、经年堆积……化为粉末……
你们以为如何: 是否她昔日的美貌魅力已然褪尽，过患显现？”
“世尊，是的。”
“比丘们，这也是形色之诱的过患。

“那么，比丘们，何为出离形色? 平息对形色的贪爱、放弃对形色的贪爱，那便是出离形色。
“凡不能如实明辨形色之诱惑为诱惑、形色之过患为过患、形色之出离为出离的僧侣行者，
他们自己理解形色、或以此真理激励他人藉修持了解形色: 那是不可能的。
然而，凡能如实明辨形色之诱惑为诱惑、形色之过患为过患、形色之出离为出离的行者，
他们自己理解形色、或以此真理激励他人藉修持了解形色: 那是可能的。”
 
“那么，比丘们，何为感受之诱？有此情形，一位比丘――远离感官欲乐、远离不善巧心态――
进入、安住于第一禅那: 由远离而生起喜与乐、伴随着寻想与评量。
那时候，他无心伤害自己、伤害他人、或伤害双方。他有一种彻底无害的感受。
我告诉你们，此无害之受，乃是一切感受中的至高诱惑。
       
“接着这位比丘，随着寻想与评估的平息，进入、安住于第二禅那; 由沈静而生起喜与乐，
随着寻想与评量的消退、知觉汇合起来――有了内在确定……
随着喜的消退，他保持着宁静、有念、警觉，身体敏感于乐。他进入、安住于第三禅那，
对此圣者们宣告:‘宁静、有念，他有了愉快的居处’……
随着乐与痛的放弃――如先前喜与苦的消退一般――他进入、安住于第四禅那:
 宁静与念住达到纯净，既无乐、又无痛。那时候，他无心伤害自己、伤害他人、或伤害双方。
他有一种彻底无害的感受。我告诉你们，此无害之受，乃是一切感受中的至高诱惑。
       
“那么，何为感受的过患？感受无常、有苦、可变: 这便是感受的过患。
那么，何为出离感受？平息对感受的贪爱、放弃对感受的贪爱，那便是出离感受。
凡不能如实明辨感受之诱惑为诱惑、感受之过患为过患、感受之出离为出离的僧侣行者，
他们自己理解感受、或以此真理激励他人藉修持了解感受: 那是不可能的。
然而，凡能如实明辨感受之诱惑为诱惑、感受之过患为过患、感受之出离为出离的僧侣行者，
他们自己理解感受、或以此真理激励他人藉修持了解感受: 那是可能的。”
 
《增支部.六集》：“那么，何为对过患的辨识、认知？
有此情形，一位比丘――来到野外、树下、空静之处――如此思索:‘这色身有诸多痛苦、诸多过患。
在这色身里会升起诸多疾病，如: 视力病、听力病、鼻病、舌病、体病、头病、耳病、口病、
牙病、咳嗽、哮喘、粘膜炎、热病、衰老、胃痛、昏迷、痢疾、流感、霍乱、麻疯、疔疮、
轮癣、肺结核、癫痫、皮肤病、痒症、痂、干癣、疥疮、黄疸、糖尿、痔疮、瘘管、溃疡、
胆症、粘液症、风症、体液症、气候症、身体照顾不周之症、外伤、业力病、冷、热、饿、
渴、排屎排尿。’ 他这般地专注于色身的过患。这便称为对过患的辨识、认知。”
 
《增支部.四集》：“这四种追求是尊贵的。哪四种？
有此情形，一个人，自己会衰老，意识到衰老的过患，寻求脱离枷锁、不老、无上的止息: 即解脱。
自己会染病，意识到染病的过患，寻求脱离枷锁、无病、无上的止息: 即解脱。
自己会死亡，意识到死亡的过患，寻求脱离枷锁、不死、无上的止息: 即解脱。
自己有杂染，意识到杂染的过患，寻求脱离枷锁、无杂染、无上的止息: 即解脱。”
 
《增支部.七集》：怒者丑陋、少眠，他所得盈利，因言行有失，转为亏损。
盛怒的人，把他的财富摧毁。狂怒的人，把他的地位摧毁。亲戚、朋友、同事们躲避他，
嗔怒带来损失，嗔怒使心燃烧。他意识不到危险由内心生起，怒者不了解自己的利益，怒者看不见法。
被嗔怒征服的人，处于一团阴暗之中。他乐于恶行，以为善行，当怒意消退之时，他如火烧般受苦。
他如烟雾围绕之火，无用、无光。
 
《相应部》：一切执取现象的过患：
“一个人连续专注于执取现象的过患，渴求便止息了。从渴望的止息，引致执取、维持的止息。
从执取、维持的止息，引致缘起的止息。从缘起的止息，引致生的止息。
从生的止息，于是老、病、死、忧、哀、痛、悲、惨，全部止息。若大一堆苦与紧张，便是这般地止息。”

《增支部.九集》：其时，尊者阿难与家主塔普萨往诣世薄伽梵，近前顶礼后，坐于一边。坐下后，他对薄伽梵说：
“这位家主塔普萨对我说：‘尊者阿难，我们是耽溺于感官之乐、欣喜于感官之乐、享受感官之乐、纵情感官之乐的家主。
在我们这些耽溺于感官之乐、欣喜于感官之乐、享受感官之乐、纵情感官之乐的人看来，出离根本是个大损失。
然而，我却听说此法此律之中，年轻的比丘们视出离为宁静，内心急于出离，趋向有信心、稳步、坚定。
因此正是在出离这个主题上，此法此律与大众背道而驰。’”
       
“正是如此，阿难，正是如此。即便我自己在觉悟前、尚为未悟的菩萨时，虽想到：‘出离善哉。退隐善哉，’
然而我的心却不急于出离，未视出离为宁静，未趋向有信心、稳步、坚定。我想：‘是何因缘、是何理由，
为什么我的心不急于出离，未视出离为宁静，未趋向有信心、稳步、坚定?’ 
接着我想到：‘我还不曾看见感官欲乐的过患。我还不曾思考那个主题。我还不理解出离的果报。我对它还不熟悉。
那就是为什么我的心不急于出离，未视出离为宁静，未趋向有信心、稳步、坚定。’”
       
“接着我想到：‘如果看见了感官欲乐的过患后，我思考该主题; 如果理解了出离的果报后，我对它熟悉起来，
我的心便有可能急于出离，视出离为宁静，趋向有信心、稳步、坚定。’”
“于是后来，在看见了感官之乐的过患后，我探索该主题，在理解了出离的果报后，我使自己熟悉它。
我的心急于出离，视出离为宁静，趋向自信、稳步、坚定。接下来，远离感官之欲、远离不善巧的心态，
我进入、安住于初禅: 从远离中升起了喜与乐，伴随着寻想与评量。”
 
《小部.自说经》――
佛陀：“跋提，听说你独自在林中、树下、空静处，反复大叫 ‘极乐! 极乐!’可是真的？”
 尊者跋提：“世尊，是真的。”
“你反复大叫‘极乐! 极乐!’时，心里在想什么？”
尊者跋提：“过去，在我居家时，为了常享君王的喜乐，我把卫兵部署于王宫内外、城镇内外、乡村内外。
即便有这等保护、这等守护，我仍住于怖畏――焦躁、多疑、恐惧。但现在，独自去林中、树下、空静处时，
我住于不惧、不躁、自信、无畏――不担心、不困扰，我的需要满足了、我的心如野鹿一般自由。
这就是我反复大叫‘极乐! 极乐!’时，心里所想的。”

接着，注意到那件事的重要性，世尊当时说偈：“不再受激者，克服有与非有者，他已超越恐惧，有喜、无悲，天神看不见他。
 
《增支部.三集》―― 佛陀：“你觉得如何：假定一位家主或家主之子有一栋房子：
山形屋顶、墙内外涂灰、门窗紧闭、无穿堂之风。在屋里，他有一张马鬃软榻：
上铺一床长羊毛褥、一床白羊毛褥、一床锦绣被、一床卡达里鹿皮毯，顶垂华盖、侧堆红枕。
点一盏灯，四个妻子百般妩媚，伺候着他。他是否能自在安眠？或者你认为如何？

阿罗毗的赫塔迦：“是，世尊，他能自在安眠。世上的自在安眠者当中，他便是一位。”
“不过年轻人，你觉得如何: 那位家主或家主之子，是否有可能升起贪欲的身火或心火――受贪火的烧灼――他苦恼难眠？”
“是，世尊。”
“然而那些贪火――受其烧灼，那位家主或家主之子苦恼难眠――该贪欲已被如来弃绝、根除，如拔起的棕榈、生机已失、永不再生。因此，他自在安眠。”

“年轻人，你觉得如何: 那位家主或者家主之子，是否有可能升起嗔怒的身火或心火――受怒火的烧灼――他苦恼难眠？”
“是，世尊。”
“然而那些怒火――受其烧灼，那位家主或家主之子苦恼难眠――该嗔怒已被如来弃绝、根除，如拔起的棕榈、生机已失、永不再生。因此，他自在安眠。
“年轻人，你觉得如何: 那位家主或家主之子，是否有可能升起痴迷的身火或心火――受痴火的烧灼――他苦恼难眠？”
“是，世尊。”“然而那些痴火――受其烧灼，那位家主或家主之子苦恼难眠――该痴迷已被如来弃绝、根除，如拔起的棕榈、生机已失、永不再生。因此，他自在安眠。”
 
《增支部.三集》：常有常有自在安眠，婆罗门已彻底解脱；他不再粘着感官欲乐，无积取，心清凉。
既已斩断一切缠缚，制服内心恐惧，平息了，他自在安眠，已达到心的寂止。
凡夫皆有生、老、死，却厌弃受其苦者，那些事他不能自免。见有情受这些苦，假如我厌弃，便不适合以同样于他们的方式生活。
持此心态，了解法，不再抓取――我克服了对健康、青春、生命的一切沈醉感，视出离为安稳。
我的力量升起，解脱清晰可见。如今再不可能求取感官欲乐。已走上梵行之道，我不回头。
 
《增支部.四集》：“有此情形，一个人已弃绝对感官欲乐的贪爱、欲望、喜爱、渴爱、狂热、执取。
接着他重病不起，在重病不起时，他不想：‘唉，我热爱的那些感官欲乐，就要离我而去了、我要被迫离开它们了！’
他不会悲伤、不会苦恼，他不哭泣、捶胸、狂乱。这便是一个面临死亡时，对死亡不惧不怕的人。”
以上佛经皆出自汉译《巴利经藏》

* 快乐是一种短暂的状态，它容易被打断，它转眼即逝
每个人都想要过快乐的生活，这是基本的人类需求，因此你必须去体验真正的快乐。

藉由拥有钱财、权势、和耽溺于感官享受的所谓快乐，并非真正的快乐。
这类的快乐非常脆弱、不稳当，而且短暂。

为了获得真正的快乐，为了永久稳当的快乐，你必须深入自己
并去除积藏在心灵深处的所有不快乐。

只要在心灵深处仍留有痛苦，那么想要在心灵表层感受到快乐的企图，都将只是白费力气。

――葛印卡老师
# 耽溺，读作dān nì，汉语词语，指无节制，无原则限制地沉湎于某种事物或某种爱好而不能自持。

每一位来参加本次会议的来宾，都是我们星球上独特族群的一员，通常都是世界上最富有、最具权势、最有成就的人。大家公认能受邀参加世界经济会议的每一位来宾，都是同业中的佼佼者。然而当一个人拥有所想要的财富、权势、和地位时，是否就必然会快乐呢？这些成就和自满就是一切了吗？或是仍有可能达到更高程度的快乐？

快乐是一种短暂的状态，它转眼即逝，此刻存在的，下一刻便消失无踪了。当你的事业、银行的帐户、家人一切都顺利时，是很快乐的。但是当不想要的事情发生了，当完全超乎掌控的事情发生并扰乱了你的快乐和和谐时又怎么样了呢？

世界上任何一个人，不管他的权势和地位如何，都会遭遇到超乎掌控的环境，和不能随心所欲的时候：可能是发现自己得了绝症、可能是亲密心爱的人病了或死了、也可能是婚姻破裂或发现另一半欺骗了你、事业成功的人可能做了一个错误的决策、公司被合并导致你失业了、政治选战输了、别人升迁到你想要的位置、小孩离家出走或是叛逆到反对你所珍惜的一切价值观。不论你有多少的财富、地位和权势，这些不想要的事情、不想要的失败总会产生极大的痛苦。
