* 非思量分别之所能解，唯有实修亲证
** 十份时间，一份阅读一份交流八分实修。 谨守身口意
1. 熟读成诵。博学多闻，只为有助宣说，对实证并非必需
   一段一段慢慢读 细细读 保持正念的读
   广闻博览 http://wiki.sutta.org/wiki/%E5%85%AB%E6%88%92
2. 戒
3. 观息 定
4. 内观 慧
** 独处，只有自己，慎独
** 四谛，八正道，十二因缘？
   苦、集、灭、道
   戒（）定（）慧（）

   布施/乐于助人、持戒/严于律己、忍辱/不卑不亢、
   精进/谦虚勤奋、禅定/专注坚定、般若/公平无私
   
   纪律和道德、耐心和毅力、专注与内观、慈悲和爱心
   注意知识、力量和智能的不同
   根器和业力，因缘
*** 异议：任何事物都有两面性，有苦必有乐？
	矛盾无时不有，无处不在。
	乐？乐的产生、乐的消失、获取乐的方法
	有哪些让我们快乐的东西？
	好吃的，好看的，好听的，好闻的，好玩儿的，
	舒适的，凉爽的，温暖的，柔滑的，安全的，
	顺心的，如愿了，被赞赏，被接受，被认同，被关心，
	被需要，能助人，
	没有债，充实而不忙碌，
	有理想并为之奋斗，有信念，有能力，有钱，
	经过努力后的收获，
	有知己
	感恩，原谅，知足，诚实守信，专注，认真，努力，坚持，
	良师益友，同情心，学而时习之，布施，慈悲，放下，照顾好自己，
	解决问题，做想做的事，活在当下，笑，冥想，
	
	知足常乐 but 知足，何其难！
	# 能让自己快乐起来的人更能得到更多的快乐！ 为什么不快乐呢？要快乐。
	美味，音乐，歌舞，轻松，健康，
	舒爽，畅快，赞赏，顺心，信仰，
	如愿，敬畏，权力，财富，助人为乐，，，
	它们来时带着快乐满足，它们去时留下烦恼空虚

	需求层次理论； 满足需求就会快乐。
	五类：生理需求、安全需求、社交需求(爱和归属感)、尊重需求和自我实现需求。
	1. 呼吸、水、食物、睡眠、生理平衡(健康）、分泌、性。
	2. 人身安全、健康保障、资源所有性、财产所有性、道德保障、工作职位保障、家庭安全
	3. 友情、爱情、性亲密
	4. 自我尊重、信心、成就、对他人尊重、被他人尊重
	5. 道德、创造力、自觉性、问题解决能力、公正度、接受现实能力
	6. 自我超越
	衣食无忧、安全、
对于不同年龄段的人会有不同的看法：
小孩子会觉得：生活中最快乐的事就是每天不用写作业，无忧无虑的玩儿。
有糖果零食，有动画片
青少年则认为：作业量不用太多，可以有闲暇的时间用来搞自己喜欢并且感兴趣的事。
青年们认为：每天打游戏，出去旅游。
成年人则想着和自己心爱的女友环游世界是最快乐的事。
中年人认为：全家人一块儿在一起吃饭，睡觉，逛公园是最快乐的事。
老年人认为：自己的儿女能常回家看看，一起吃一个团圆饭则是最快乐的事。
总之，有一颗良好的心态，那才是最快乐的事~~~~	

* 一切都失去了光彩，失去了意义
  任何的安慰，各种鸡汤，都显得苍白乏力
  何时？
  幻象？真实？

  预期 憧憬 想象 幻想 | 现实 真实
* 信
  佛陀做为心灵导师的成功程度，完全取决于他训练弟子的技巧。

经典中为礼敬佛陀而称他为“无上士调御丈夫”①，
要检验这句话的真实度，就必须去看他所指导的男女弟子的气度。
就如太阳的价值，不只在它本身的光明，同时也在它照亮世间的能力一样。
因此，佛陀作为心灵导师的光辉，不只是取决于他教法的清晰度，
更是在他能启发前来求皈依者与因材施教。缺少弟子团体见证它转化的力量，
“法”（Dhamma）将只是学说与严谨修持的包裹，徒有令人钦佩的清晰与精确的理智，
但都与活生生的人无关。“法”只有在接触生命，提升它的追随者，
经他们转化为智慧、慈悲与清净的典范时，“法”才会有生命。

* 上班地铁上想起一个话题
每一天如何过才是有价值的呢？ 有钱有名有闲有健康有声色犬马
人生天地之间，若白驹过隙，忽然而已 ―― 庄子《知北游》

 有没有价值，有个非常简单的标准：每天是不是快乐开心。 就可以判断。
 如果发现自己常常不高兴，甚至每天都不高兴，那就一定出问题了。
 快乐就好。
 话是这样说， 还是有许许多多人是苦苦的过着每分每秒，或是麻木的过着分分秒秒。
对酒当歌，人生几何？譬如朝露，去日苦多。
青青子衿，悠悠我心；何以解忧？唯有肚肠

 有没有想过自己的三年五年或十年的目标？
 那么人生的目标呢？
 几个非常明确的例子：
 佛教是证入涅，基督教是进入天国，马克思主义者是共产主义，秦始皇是统一六国，
 体育运动员是金牌（挑战极限，突破极限），一般人是“成功”：有名有钱有时间，有健康

 # 什么是有益的,有价值的,被圣人称赞的，能导向涅的
 另一层面，生物界一个共同的目标是繁衍后代，传宗接代。
 追逐和享受感官欲乐，

・ 人生应该如蜡烛一样,从顶燃到底,一直都是光明的.―― 萧楚女
・ 人只有献身于社会,才能找出那短暂而有风险的生命的意义.―― 爱因斯坦
・ 人生的价值,即以其人对于当代所做的工作为尺度.―― 徐玮 
・ 但愿每次回忆,对生活都不感到负疚 ―― 郭小川 
・ 你若要喜爱你自己的价值,你就得给世界创造价值.―― 歌德 
・ 人生不是一种享乐,而是一桩十分沉重的工作.―― 列夫 ・ 托尔斯泰 
・ 人生的价值,并不是用时间,而是用深度去衡量的.―― 列夫 ・ 托尔斯泰
生命中真正重要的不是你遭遇了什么，而是你记住了哪些事，又是如何铭记的。――马尔克斯《百年孤独》
一个人知道自己为什么而活，就可以忍受任何一种生活。―― 尼采

作者：罗鹏
链接：https://www.zhihu.com/question/20447176/answer/19587501
人生观，你想成为什么样的人？
人生观是你对自己这一生总体的期待，你觉得作为一个人，就应该这样这样这样。
比如你是想成为有钱人，过别人羡慕的富裕生活；
还是想成为高官，用权力来服务人民(也可能是为了赚钱)；
还是想成为一个旅行者，去体验世界的精彩；
还是想成为一个老师，教书育人；
还是想成为一个有思想的人，有智慧的人，不让自己活得糊涂；
还是就想做一个普通人，有车有房，安稳的过日子......

价值观，对你来说什么更重要？人在做决定的时候，都会依靠内心的一套价值体系，
选择一个相对而言更值得的去做。
在你的这个价值体系里面，借钱的时候金钱更重要还是朋友更重要，
找女朋友的时候外表更重要还是品行更重要，跳槽时薪水更重要还是平台发展更重要，
周末享受生活更重要还是为事业学习更重要......

世界观，世界是什么样的？整体来说，世界观是庞杂的、模糊的。
但这不重要，重要的是要认识到世界是客观的，
我们中的大部分人都习惯于带着成见去看待现实世界，并把偏见强加于自己的现实观。
我们学会了依靠观念来理解现实（而不是通过观察），去假定现状与我们观念中预想的相似，
这比自己亲眼观察现状要来得方便。
举个例子，我个人认为世界是由需求驱动的，你是个什么样的人不重要，
重要的是你能满足别人什么需求。

最后强调一点，人生观、价值观、世界观是不断变化的，根据你的知识结构、
主观意识的改变而改变，这也是一个再正常不过的过程，永远没有极致。


任何一件事情，只要心甘情愿，总是能够变得简单。 ――安妮宝贝《彼岸花》

所有的大人都曾经是小孩，虽然，只有少数的人记得。
令她反感的，远不是世界的丑陋，而是这个世界所戴的漂亮面具。
每个圣人都有不可告人的过去，每个罪人都有洁白无瑕的未来。

这是一个最好的时代，这是一个最坏的时代； 
这是一个智慧的年代，这是一个愚蠢的年代； 
这是一个光明的季节，这是一个黑暗的季节； 
这是希望之春，这是失望之冬； 
人们面前应有尽有，人们面前一无所有； 
人们正踏上天堂之路，人们正走向地狱之门。
  ―― 狄更斯《双城记》

井蛙不可以语于海者，拘于虚也；夏虫不可以语于冰者，笃于时也；曲士不可以语于道者，束于教也。
――庄子《秋水》
从来没有人读书，只有人在书中读自己，发现自己或检查自己。 ―― 罗曼・罗兰

* 障碍 束缚 结使

这些难关便是：

贫穷时，布施助人难
富贵时，学习佛法难
舍弃自己的性命难
能够听经学佛难
生在佛法在世的时代难
控制自己的感情欲望难
遇到珍贵东西不奢求难
被侮辱不嗔恨难
有权势不居高难
与外境接触不动心难
广泛学习博览群书难
消灭自我的傲慢难
不轻视不懂学法的人难
对万物持平等心难
不说是非对错难
遇到大德善知识难
明心见性地学习难
随缘教化他人难
遇到境界并不为所动难
明白方便法以教化众生难

这二十难，我们需要记在心里，作为对境，时时自省吾身......

* 思
贪求、执取
预期 憧憬 想象 幻想 | 现实 真实

最小化，能不做就不做；最大化，力所能及的多做。 转变，时间如何度过？

获取关注 认同 或敬畏。喂养六条饿狼，眼耳鼻舌身意，六欲

最终的大boss - 性

存在感 我见 是怎么产生的？

学深刻地体验到真正的空无自性，是极大的喜悦，此时心变得无所执取，并且清澈而明亮。
如何验证？ 找到最“在意”的，丢弃它会怎样？ 比如，删掉收藏的图片视频文章好友等等
如何检验？ 若有良田千顷，家奴无数，富贵荣华，会否舍弃一切，清修悟道？

昏沉 散乱 邪淫 难戒 如之奈何？ 如何做？ 熟读成诵，如健身一样奋力锻炼心力
平静平稳、警觉专注、非常的警觉非常的专注、十分的警觉十分的专注

休息，而不是放弃

忽然想到一个游戏， 如果人和人交往的时候，完全诚实， 会是一种什么状况？

勿顾虑别人的过失，也勿顾虑别人有否作善或作恶；只须留心自己的过失，以及留心自己有否作善或作恶。
常思己过，莫论他非。

兴高采烈  欢欣鼓舞； 无精打采 百无聊赖

* 闻
http://www.dhammarain.org.tw/magazine/new/dhammarain-mag-004.html
http://www.dhammarain.org.tw/
http://www.dhammarain.org.tw/magazine/rainall.html

   本书是一部心灵之旅，它带领你参访许多佛法的系统和师父。
表面上，他们也许各有不同，甚至彼此矛盾，
然而，我们无须相互比较，评定优劣。
这些言语和系统底下都是唯一真理的不同展现。
法是不变的，正如草叶的低垂和云朵的飘动显示有风的存在，
大师们的文字和教诲也都指向相同的体验、相同的真理。

大唐西域记，瑜伽师地论，成唯识论

本书最有效的使用方式，是依照它们最初的写法，
即为了激励与薰陶心灵的目的而阅读；不应存着阅读小说的心态来读。
在此建议读者，一天最好不要阅读超过一章，
应该和你正在学习的某个特殊弟子“交朋友”，
思维他或她的生命与教导，并试着发现那些故事对现代人有何启发。
最快也要等到隔天，才可以进行下一章。
你的心可能会迷恋这些事，因此最好克制一下好奇心，
并不断提醒自己为何阅读这本合集的原因。


沙利子是个名副其实的真实朋友，他了解如何做对别人最有利，
像佛陀所描述的理想朋友一样，直言不讳地指出朋友的过错，毫不迟疑。
就是透过这种诚实的批评，他帮助阿奴卢塔尊者突破最后关卡，证得阿拉汉果，
如《增支部》的记载：

有一次阿奴卢塔去看沙利子，相互寒暄之后，他便坐下来对沙利子说：
“沙利子吾友，我以超越世人眼界的清净天眼，可以看见大千世界。
我精进不懈，正念、正知且无疑惑；我的身体平静无忧扰，我的心专注于一处。
然而，我的心却仍未从烦恼与贪着中解脱。”
“阿奴卢塔吾友，”沙利子说，“当你想到你的天眼时，慢心就生起了；
当你想到自己坚定的精进、正念、无忧扰的色身与专注一处的心时，掉举就产生了；
当你想到你的心不能从烦恼解脱时，这就是恶作。如果你能舍弃这三种心境，
不再注意它们，这将会对你有所助益，就能将心引导到‘不死界’。”

阿奴卢塔遵从沙利子的建议，很快便断除烦恼。


现实中很多人把爱情理想化，缺乏现实感，总希望自己的爱情像小说电视剧那般浪漫：
月白风清，白马王子突然从天而降；一见钟情，爱情之花突然奇迹般地大放光彩

* 疑 疑问 疑虑 
疑虑：都出家，人类就消失了; 耕作者出家了，其他家人怎么办？
疑问：若无一个延续不断的灵魂，那么业报是如何运作的呢

闻思修 戒定慧  信愿行 佛法僧

* 读书，并非百利无害
  非圣书，屏勿视，蔽聪明，坏心志。
  过犹不及，不要花费太多时间读书。
  万般皆下品惟有读书高，警惕这种优越感。
  纸上谈兵，变成书呆子。尽信书则不如无书。
  读书使人明智，但明智的后果未必是带来快乐。

* 7种让人越来越蠢的认知偏差
  https://www.zhihu.com/question/37723905
https://mp.weixin.qq.com/s?__biz=MjM5NTU0NTYxNA==&mid=2652647409&idx=1&sn=f6b0a9b701b85eb2bec60f6b0c23714f&chksm=bd1e58908a69d186407cf8096a546c5d65f297d45d283e816617e176ff97b619b9196bd32410&mpshare=1&scene=1&srcid=08103CGa3dZ4da8oAKjT2bzG#rd
1.自利归因偏差(self-serving bias）
成功时，觉得多半是自己的功劳；失败时，甩锅给别人或外界环境。
# 对治：常思己过，莫论他非

2.行动者-观察者偏差(actor-observer effect)
我们观察别人的行为时，倾向于指责别人的人品，而忽视情境的影响。
人在矮檐下，怎能不低头
# 对治：设身处地，换位思考

3.错误定价（misvaluation hypothesis）
你对一件事的定价，就是你认为，这件事带给你的价值。
之所以会有错误定价偏差，是因为很多人，只定价了一件事的短期价值。
例，明明知道电子游戏，休闲时玩一玩即可，可很多人心中，游戏的「定价」奇高，因为追求即时的愉悦感，他们打游戏茶饭不思。
读书学习，短期看不到价值，他们便放弃；游戏，短期获得了快感，就拼了命地玩。
# 对治：？

4.过度自信偏差（overconfidence theory）
如果你正确定价了读书，明白读书的重要了……还可能陷入另一种偏差。
比如「今年我一定要读100本书！」，或者朋友圈集赞「你们给我点几个赞，今年我就要读几本书！」。
心理学家把人的这种迷之自信，叫做过度自信偏差。
# 对治：看看自己的前半生，做个简单的计划，行动吧

5.沉没成本效应(sunk cost effects)
上高中那会，共享车还没出世，有时早上起迟了，准备打的却苦苦等不到，反倒是公交车过去好几辆，我却还是想打的，
心想：“我都等了这么久的的士，得继续等下去，要不然先前花的时间不白费了？”

我的做法其实是很蠢的，这是典型的沉没成本效应。
等的士花的时间，就是我不可挽回的成本，却影响了我的决策，宁愿继续等下去也不愿坐公交……

谈恋爱时也一样，对方毅然决然提分手，你心想：“都谈一年了，付出了那么多，怎能轻易结束？”
可……Ta已经不爱你了，挽留不成，却还是要死缠烂打。
这不是蠢，是什么？
过去的牺牲和付出，就让它过去吧，如果不能把过去的痛苦和牺牲留在身后，那和身居牢狱有什么区别？
# 对治：站在当下，往前看
6.后视偏差（hindsight bias）
事后诸葛亮，事前猪一样。
# 对治：事先做足准备工作；丑话说在前头
7.幸存者偏差（survivorship bias）
常常看见这样的报道： 从月薪3000逆袭估值30亿估值企业CEO，他有什么秘诀？
打开文章，通常先讲一个潘磕嫦的故事，然后总结出123条道理，告诉读者这就是秘诀……
心理学家称之为幸存者偏差，千千万万个月薪3000的人里，只有他是「幸存者」，上了媒体报道，其他99.9%的人都「死了」。

大部分人只看到成功人士讲的大道理，却没看到背后的方法论、资源、家境、人脉甚至运气成分。
# 对治：

远离认知偏差，有这3个步骤：
1.改变你的元认知
认识到认知偏差的存在本身，就能削弱它的影响。

这个过程，其实调用你的元认知能力，即对思考过程的反思：
只有意识到思考过程中偏差的存在，才能去改变它，元认知为思考过程按下了停止键。

2.没错，你应该对号入座
认识到还不够，现实里的认知偏差往往很隐蔽，所以一定要联系你的现实经历。
比如：过去我犯过哪些偏差？将来，碰到同样的情况，才会想起来去避免。

3.慢下来，慢下来，慢下来
每天都能看到这样的标题：
几节课颠覆你的认知，几天教你把月薪提高十倍，几条秘诀教你成为高手……

无数的课程、文章，都号称能颠覆你的三观。
于是你心动了，点了购买，去感受「迅速」颠覆三观的感觉。

这个时代太「快」了。
它鼓动你迅速成功、鼓动你迅速购买、鼓动你迅速思考......

商家利用人性、利用心理陷阱、利用认知偏差，操纵你的钱包。
所以我建议你：在做任何决定前，给自己一些思考的时间，慢下来，慢下来，慢下来。

快，是时代病。
慢，是良药。

* 价值或意义
  人的生存只有两种：“美丽的活着”，亦或“为美丽的人活着”。――尼克 《东京食尸鬼》
