软件设计 = 需求 + 合适的技术组合。 设计就是选择合适的技术组合，满足用户的需求。
* 引言
** 编写目的和范围
   程序设计，是选择合适的技术组合，满足用户需求的过程。
   本详细设计说明书编写的目的是说明程序模块的设计考虑，包括程序描述、输入/输出、算法和流程逻辑等，
   为软件编程和系统维护提供基础。本说明书的预期读者为系统设计人员、软件开发人员、软件测试人员和项目评审人员。
** 术语表
   定义系统或产品中涉及的重要术语，为读者在阅读文档时提供必要的参考信息。
** 参考
   列出有关资料的名称、作者、文件编号或版本等。参考资料包括：
   a．需求说明书、架构设计说明书等；
   b．本项目的其他已发表的文件；
   c．引用文件、资料、软件开发标准等。
   会议记录的需求点。
   微信官方文档。
* 总体设计
** 需求规定
** 运行环境
   物理结构，系统流程，设备清单
   客户端：手机、平板
   服务器：已备案的域名、80和443端口
** 基本设计概念和处理流程
   软件结构，模块清单
   用户身份认证、文档转图片、加密传输、图片显示和放缩。
* 全局数据结构说明
** 常量
   包括数据文件名称及其所在目录，功能说明，具体常量说明等。
   服务器域名：ssmp.sursenelec.com
** 变量
** 数据结构
   包括数据结构名称，功能说明，具体数据结构说明（定义、注释、取值）等。
* 模块设计
** 用例图
   # 手绘拍照
** 功能设计说明
*** 模块1 -- 登录
	简要描述子模块1的业务功能。
	用户身份验证
**** 输入数据
	 用户名、密码
**** 输出数据
	 登录后的页面：包含什么内容？
**** 业务算法和流程
	 输入用户名和密码，提交登录，服务器验证身份，返回结果，客户端展示结果。
**** 数据设计
**** 源程序文件说明
**** 函数说明
**** 限制条件
**** 其他说明
*** 模块2 -- 审阅文件
**** 输入数据
	 文件标识
**** 输出数据
	 文件快照
**** 业务算法和流程
	 用户打开文件，客户端发送请求到服务器，服务器查找文件，并转换为图片，返回到客户端。
**** 数据设计
**** 源程序文件说明
**** 函数说明
**** 限制条件
**** 其他说明
 * 接口设计
** 内部接口
** 外部接口
*** 接口说明
	例如：xx子系统通过xx从xx子系统取得xx等，相关标准，调用示例，可根据需要增加章节描述接口。
*** 调用方式
	例如：内部接口调用：
	例: 
	/**
	*通过用户服务号码取得该客户认证密码等信息，如果该客户存在返回为0，其他情况参考错误编码
	*/
	public  RUserInfo  getUserInfo (String userNo);
* 数据库设计
* 系统安全保密设计
** 说明
** 设计
*** 数据传输部分
*** IP过滤部分
*** 身份验证部分
* 系统性能设计
* 系统出错处理
  例如：为了在系统出现异常情况下给用户以明确的提示，可采用两种方式予以提示：
  1．使用Javascript的alert()函数直接提示，这主要在输入或修改的情况下使用；
  2．使用统一的错误界面提示，该界面对应于errorpage.jsp页面。错误界面样式如下图所示：
* 系统维护计划
